const WORDS = [
  {en: "(Sought V2)", tr: "(Aranan V2)"},
  {en: "(with) Frustration", tr: "Hüsran"},
  {en: "… at most", tr: "En fazla"},
  {en: "…. after…. (….= day, night)", tr: "Her Allahın …."},
  {en: "A fit of +", tr: "Kriz"},
  {en: "A measure of", tr: "Önemli derecede"},
  {en: "A swath of", tr: "Bir grup"},
  {en: "Abandone", tr: "Terk etmek"},
  {en: "abide by", tr: "…e uymak"},
  {en: "Ability to V1", tr: "Yetenek"},
  {en: "Abrupt", tr: "Birden, aniden"},
  {en: "Absolve of", tr: "Aklamak"},
  {en: "abstain from", tr: "kaçınmak"},
  {en: "absurd", tr: "saçma"},
  {en: "Abundance", tr: "Bolluk"},
  {en: "accelerate", tr: "hızlandırmak"},
  {en: "accessible", tr: "erişilebilir"},
  {en: "Acclaimed", tr: "Övülen"},
  {en: "Accomplish", tr: "Başarmak"},
  {en: "account for", tr: "oluşturmak"},
  {en: "acknowledge", tr: "Kabul"},
  {en: "act out", tr: "canlandırmak"},
  {en: "Actively", tr: "Bilerek, isteyerek"},
  {en: "acute", tr: "akut"},
  {en: "Adamant", tr: "Sözünün arkasında, kararlı"},
  {en: "adapt", tr: "uydurmak"},
  {en: "adhere", tr: "Uygun"},
  {en: "adhere to", tr: "…e uymak"},
  {en: "Administration", tr: "İdare"},
  {en: "Adopt", tr: "Sahiplenmek"},
  {en: "Adornment", tr: "Süs eşyaları"},
  {en: "adverse", tr: "Olumsuz"},
  {en: "Adversity", tr: "Zorluklar, zor durumlar"},
  {en: "Advice", tr: "Tavsiye"},
  {en: "Advise", tr: "Tavsiye etmek"},
  {en: "advocate", tr: "avukat"},
  {en: "Aerial", tr: "Anten"},
  {en: "Affair", tr: "İlişki"},
  {en: "Affection", tr: "Sevgi, şevkat"},
  {en: "affirm", tr: "Teyit"},
  {en: "affluent", tr: "zengin"},
  {en: "Afford", tr: "Madden gücü yetmek"},
  {en: "After all", tr: "Neticede"},
  {en: "Agenda", tr: "Gündem"},
  {en: "Aggregate", tr: "Küme"},
  {en: "Ahead of us", tr: "Önümüzde (zamansal olarak)"},
  {en: "Ailment", tr: "Hafif hastalık"},
  {en: "Air", tr: "Yayınlamak"},
  {en: "Airstrip", tr: "Uçak pisti"},
  {en: "Aisle", tr: "Koridor"},
  {en: "Alarm", tr: "Korkutmak"},
  {en: "Algae", tr: "Alg"},
  {en: "alienate", tr: "Yabancılaştırmak"},
  {en: "All in all", tr: "Kısacası"},
  {en: "alleged", tr: "Iddia"},
  {en: "All-out", tr: "Tam"},
  {en: "Allowance", tr: "Harçlık"},
  {en: "allude", tr: "Ima"},
  {en: "Almost overnight", tr: "Neredeyse her gece"},
  {en: "alter", tr: "değiştirmek"},
  {en: "alternative", tr: "alternatif"},
  {en: "Alternative", tr: "Seçenek, şık"},
  {en: "Altruistic", tr: "Fedakar"},
  {en: "Ambidexterous", tr: "Her iki kol ve bacağını kullanabilen"},
  {en: "Ambivalence", tr: "Kafa karışıklığı"},
  {en: "Amiable", tr: "Sevimli, cana yakın"},
  {en: "Among other things", tr: "Ve daha pekçok"},
  {en: "Amoral", tr: "Ahlaksız"},
  {en: "ample", tr: "büyük"},
  {en: "Ancestor", tr: "Ata"},
  {en: "Ancient", tr: "Kadim, çok eski"},
  {en: "anecdote", tr: "anekdot"},
  {en: "Animosity", tr: "Husumet, düşmanlık"},
  {en: "Annexation", tr: "İlhak, topraklarına katma"},
  {en: "Annoy", tr: "Can sıkmak"},
  {en: "Anoint", tr: "Merhem"},
  {en: "anonymous", tr: "Anonim"},
  {en: "Anthem", tr: "Marş"},
  {en: "antidote", tr: "panzehir"},
  {en: "Anyone (olumlu cümlelerde)", tr: "Herkes"},
  {en: "Anyway", tr: "Zaten"},
  {en: "apathy", tr: "duygusuzluk"},
  {en: "Appeal", tr: "Çekmek (attract), Yakarmak, yalvarmak, Talepte bulunmak, Temyize gitmek"},
  {en: "Appliance", tr: "Elektrikli ev aletleri"},
  {en: "Appraisal", tr: "Değerlendirme"},
  {en: "Appreciate", tr: "Takdir etmek"},
  {en: "apprehensive", tr: "endişeli"},
  {en: "Approach", tr: "Yaklaşmak"},
  {en: "appropriate", tr: "uygun"},
  {en: "Aquatic", tr: "Suda yaşayan, su ile alakalı"},
  {en: "Arduous", tr: "Zorlu, çetin"},
  {en: "arrogant", tr: "kibirli"},
  {en: "As", tr: "1) İken 2) Çünkü 3) Gibi"},
  {en: "As a means of", tr: "İn ın yoluyla"},
  {en: "As far back as", tr: "Taa"},
  {en: "As long as", tr: "Mümkün olduğunca, yeter ki"},
  {en: "As much", tr: "Aynı derecede"},
  {en: "As much as I could", tr: "Elimden geldiğince"},
  {en: "As we know it", tr: "Hepimizin bildiği gibi"},
  {en: "As…as they could", tr: "Olabildiğince"},
  {en: "ascend", tr: "tırmanmak"},
  {en: "Ascertain", tr: "Tespit etmek, belirlemek"},
  {en: "Assassination", tr: "Suikast"},
  {en: "Assembly instruction", tr: "Kurulum talimatları"},
  {en: "assess", tr: "değerlendirmek"},
  {en: "Assignment", tr: "Ödev"},
  {en: "Astounding", tr: "Şaşırtıcı"},
  {en: "Astute", tr: "Kurnaz"},
  {en: "At a time", tr: "Tek seferde"},
  {en: "At any time", tr: "Her an"},
  {en: "At least …", tr: "En az"},
  {en: "At length", tr: "Uzun uzadıya"},
  {en: "At the last minute", tr: "Son dakikada"},
  {en: "At this rate", tr: "Böyle giderse"},
  {en: "Atrocious", tr: "Elverişsiz"},
  {en: "Attain", tr: "Ulaşmak"},
  {en: "Attempt", tr: "Girişim, girişmek, kalkışmak"},
  {en: "Attendant", tr: "Hizmetli"},
  {en: "Attentively", tr: "Dikkatli"},
  {en: "Attest to", tr: "Doğruluğuna tanıklık etmek"},
  {en: "Attic", tr: "Tavan arası"},
  {en: "Attitude", tr: "Tavır"},
  {en: "Attractive", tr: "Çekici"},
  {en: "Auction", tr: "Açık artırmayla satmak"},
  {en: "audible", tr: "işitilebilir"},
  {en: "Autonomous", tr: "Özerk"},
  {en: "Avalanche", tr: "Çığ"},
  {en: "avert", tr: "önlemek"},
  {en: "Avian", tr: "Kuş"},
  {en: "Award for", tr: "Ödül"},
  {en: "awe", tr: "huşu"},
  {en: "Back down", tr: "Geri adım atmak"},
  {en: "back up", tr: "desteklemek"},
  {en: "Bad-tempered", tr: "Huysuz"},
  {en: "Ballet", tr: "Balet"},
  {en: "Ban on", tr: "Yasak"},
  {en: "Banquet", tr: "Ziyafet"},
  {en: "Bargain (n)", tr: "Kelepir, ucuz mal"},
  {en: "Bargain (v)", tr: "Pazarlık etmek"},
  {en: "Barley", tr: "Arpa"},
  {en: "Barn", tr: "Ahır, samanlık"},
  {en: "Barracks", tr: "Kışla"},
  {en: "Barrage", tr: "Akın, sel"},
  {en: "Basement", tr: "Bodrum"},
  {en: "Bathroom tissue", tr: "Tuvalet kağıdı"},
  {en: "Battle", tr: "Savaş"},
  {en: "Be cleared for", tr: "… için izinlisin"},
  {en: "Be in the best interest", tr: "Çıkarına/faydasına olacak"},
  {en: "Be really into ving", tr: "Seviyorum"},
  {en: "Be required to v1", tr: "Yapması gerekmek"},
  {en: "Beam", tr: "Sütun"},
  {en: "Bear", tr: "Dayanmak"},
  {en: "Beast", tr: "Canavar"},
  {en: "Bed-in", tr: "Yatalak"},
  {en: "Beet", tr: "Pancar"},
  {en: "Being", tr: "Yaratık"},
  {en: "Belief", tr: "İnanış"},
  {en: "Believe", tr: "İnanmak"},
  {en: "Beneath", tr: "Altındaki"},
  {en: "Besiege", tr: "Kuşatılmak"},
  {en: "bestow", tr: "Bestow"},
  {en: "Bestow sth on sb", tr: "Sunmak, (ödül, takdir belgesi) vermek"},
  {en: "Beware", tr: "Dikkat etmek"},
  {en: "Bid", tr: "İhale"},
  {en: "Binder", tr: "Ciltçi"},
  {en: "Binocular", tr: "Dürbün"},
  {en: "Bituminous", tr: "Bitümlü"},
  {en: "Blackmail", tr: "Şantaj"},
  {en: "bland", tr: "Müla -yim"},
  {en: "Blast", tr: "Büyük patlama"},
  {en: "Blew", tr: "Uçurmak"},
  {en: "Blister", tr: "Su toplamak"},
  {en: "Blossom", tr: "Çiçek"},
  {en: "blunt", tr: "kör"},
  {en: "Body work", tr: "Kaporta"},
  {en: "Bog", tr: "Bataklık"},
  {en: "Bogg down", tr: "Gömülüp kalmak"},
  {en: "Boisterous", tr: "Şamatacı, gürültücü"},
  {en: "Bolt", tr: "Fırlamak"},
  {en: "Bonus", tr: "İkramiye"},
  {en: "Boo", tr: "Yuh çekmek"},
  {en: "Boost", tr: "Hızla artırmak"},
  {en: "Bore", tr: "Sıkıcı insan"},
  {en: "Boredom", tr: "Sıkıntı"},
  {en: "Borrow", tr: "Ödünç almak"},
  {en: "Bossy", tr: "Buyurgan"},
  {en: "Bother", tr: "Rahatsız etmek, zahmet etmek"},
  {en: "Boulder", tr: "Büyük kaya kütlesi"},
  {en: "Bounce", tr: "Zıplamak"},
  {en: "Bounce back", tr: "Toplamak, iyileşmek"},
  {en: "Bound to", tr: "Kesinlikle …cek/cak"},
  {en: "Bouquet", tr: "Buket"},
  {en: "Box ear", tr: "Kulağını çekmek"},
  {en: "Boxing", tr: "Boks"},
  {en: "break down", tr: "bozulmak"},
  {en: "break into", tr: "zorla girmek"},
  {en: "break out", tr: "patlak vermek"},
  {en: "Breakthrough", tr: "Çığır, yenilik, atılım"},
  {en: "Breed", tr: "Beslemek"},
  {en: "Bribe", tr: "Rüşvet"},
  {en: "Brick", tr: "Tuğla"},
  {en: "Bright spot about", tr: "Birşeyin güzel yanı"},
  {en: "bring about", tr: "neden olmak"},
  {en: "bring on", tr: "neden olmak"},
  {en: "Brisk (genellikle walkla)", tr: "Hızlı, çevik, atik"},
  {en: "Broke", tr: "Züğürt, beş parasız"},
  {en: "Broom", tr: "Süpürge"},
  {en: "Bruise", tr: "Morluk"},
  {en: "Bubbly", tr: "Köpüklü"},
  {en: "Budge", tr: "Kıpraşmak"},
  {en: "Budget", tr: "Bütçe"},
  {en: "Bully", tr: "Zorba"},
  {en: "bump into", tr: "karşılaşmak"},
  {en: "Burden", tr: "Yük"},
  {en: "Burial", tr: "Mezar"},
  {en: "Burst into flames", tr: "Alevlere boğulmak"},
  {en: "Burst into laughter", tr: "Kahkaya boğulmak"},
  {en: "Burst into tear", tr: "Gözyaşına boğulmak"},
  {en: "Bury", tr: "Gömmek"},
  {en: "Business course", tr: "İşletme dersi"},
  {en: "Butcher", tr: "Kasap"},
  {en: "By far", tr: "Açık ara"},
  {en: "By heart", tr: "Ezbere"},
  {en: "By Ving", tr: "-erek, -arak"},
  {en: "Cab", tr: "Taksi"},
  {en: "Cabbage", tr: "Lahana"},
  {en: "Calamity", tr: "Felaket"},
  {en: "Call", tr: "Ziyaret etmek"},
  {en: "call for", tr: "gerektirmek"},
  {en: "call off", tr: "iptal etmek"},
  {en: "Call on", tr: "Seslenmek"},
  {en: "Call upon", tr: "Çağrıda bulunmak"},
  {en: "Calm", tr: "Sakin"},
  {en: "Came as no suprise", tr: "Hiç şaşırtmadı"},
  {en: "Campaign", tr: "Sefer"},
  {en: "Can’t help Ving", tr: "Den edememek"},
  {en: "Canal", tr: "Kanal"},
  {en: "candid", tr: "Samimi"},
  {en: "Canopy", tr: "Örtü (doğa, bitki)"},
  {en: "Canvas", tr: "Tuval"},
  {en: "Captain", tr: "Yüzbaşı"},
  {en: "Captive", tr: "Esir"},
  {en: "Cardigan", tr: "Hırka"},
  {en: "Care", tr: "Umursamak"},
  {en: "Carefree", tr: "Kaygısız"},
  {en: "Caring", tr: "Şefkatli"},
  {en: "Carpentry", tr: "Marangozculuk"},
  {en: "carry on", tr: "devam etmek"},
  {en: "carry out", tr: "yürütmek"},
  {en: "Carve", tr: "Oyarak, kazarak açmak"},
  {en: "Carving", tr: "Duvar resmi (oyma)"},
  {en: "Cast", tr: "Alçı"},
  {en: "Casual", tr: "Günlük"},
  {en: "Cataclysm", tr: "Felaket"},
  {en: "catch on", tr: "moda olmak"},
  {en: "Catch up on", tr: "Yetişip bitirmek"},
  {en: "catch up with", tr: "yetişmek"},
  {en: "Cautious", tr: "Tedbirli"},
  {en: "Cavity", tr: "Çürük"},
  {en: "Ceiling", tr: "Tavan"},
  {en: "Celestial body", tr: "Gök cisimleri"},
  {en: "Cellar", tr: "Kiler"},
  {en: "Cement", tr: "Çimento"},
  {en: "Cemetery", tr: "Mezarlık"},
  {en: "Cereal", tr: "Kahvaltı gevreği, Müsli"},
  {en: "Certain", tr: "Belli"},
  {en: "Chalkboard", tr: "Tahta"},
  {en: "Challenging", tr: "Zorlu, çetin"},
  {en: "Chamber", tr: "Oda"},
  {en: "Chant", tr: "Yüksek sesle tekrar etmek"},
  {en: "Charity", tr: "Hayır kurumları"},
  {en: "Charm", tr: "Cazibe, büyüleme"},
  {en: "Chase", tr: "Takip etmek, kovalamak"},
  {en: "Cheat", tr: "Sahtekâr, dolandırıcı"},
  {en: "Cheer", tr: "Tezahürat yapmak"},
  {en: "Cheerful", tr: "Neşeli"},
  {en: "Chest", tr: "Sandık,göğüs kafesi"},
  {en: "Chew", tr: "Çiğnemek"},
  {en: "Chimney", tr: "Baca"},
  {en: "Chip", tr: "1. Küçük parça 2. Tek yönlü çatlak"},
  {en: "Choir", tr: "Koro"},
  {en: "Chores", tr: "Angarya işler"},
  {en: "chronic", tr: "kronik"},
  {en: "chronological", tr: "kronolojik"},
  {en: "Chunk", tr: "Parça"},
  {en: "Chunking system", tr: "Eş ve zıt anlamlılar birlikte"},
  {en: "Cinnamon", tr: "Tarçın"},
  {en: "Circumlocation", tr: "Lafı eveleyip gevelemek"},
  {en: "Circumstances beyond my control", tr: "Elimde olmayan koşullardan dolayı"},
  {en: "cite", tr: "Cite"},
  {en: "Clap", tr: "Alkışlamak"},
  {en: "Clay", tr: "Kil"},
  {en: "Cleared for", tr: "İçin izinlisin"},
  {en: "Clerk", tr: "Tezgahtar, katip"},
  {en: "Clumsy", tr: "Sakar"},
  {en: "Clutches", tr: "Koltuk değnekleri"},
  {en: "Coal", tr: "Kömür"},
  {en: "Coarse", tr: "Kaba"},
  {en: "Coast", tr: "Kıyı"},
  {en: "coerce", tr: "zorlamak"},
  {en: "Coffin", tr: "Tabut"},
  {en: "coherent", tr: "yapışık"},
  {en: "Collapse", tr: "Çökmek"},
  {en: "Collar", tr: "Yaka"},
  {en: "College", tr: "Üniversite"},
  {en: "Collide with", tr: "Çarpışmak"},
  {en: "Collision with", tr: "Çarpışma"},
  {en: "Colonial", tr: "Sömürge"},
  {en: "Combustion", tr: "Yanma"},
  {en: "come about", tr: "gerçekleşmek"},
  {en: "come across", tr: "karşılaşmak"},
  {en: "Come down = decrease", tr: "Aşağı inmek = azalmak"},
  {en: "come up with", tr: "bulmak"},
  {en: "Commercial", tr: "Ticari, TV radyo reklamı"},
  {en: "Commercial break", tr: "Reklam arası"},
  {en: "Commit", tr: "İşlemek"},
  {en: "Commitment", tr: "Sadakat, bağlılık"},
  {en: "Communal", tr: "Müşterek"},
  {en: "Commute", tr: "İşe gidip gelmek"},
  {en: "Compansate", tr: "Uygun ödemeyi yapmak, bedelini ödemek"},
  {en: "comparable", tr: "karşılaştırılabilir"},
  {en: "compatible", tr: "uyumlu"},
  {en: "compel", tr: "zorlamak"},
  {en: "compensate", tr: "telafi etmek"},
  {en: "competent", tr: "Yetkili"},
  {en: "Compilation", tr: "Koleksiyon"},
  {en: "compile", tr: "derlemek"},
  {en: "Complaint", tr: "Yakınma"},
  {en: "Compliment", tr: "İltifat"},
  {en: "comply", tr: "uymak"},
  {en: "comply with", tr: "…e uymak"},
  {en: "Comprehensive", tr: "Kapsamlı"},
  {en: "Conceal", tr: "Gizlemek, saklamak"},
  {en: "concede", tr: "teslim etmek"},
  {en: "conceive", tr: "anlamak"},
  {en: "concise", tr: "özlü"},
  {en: "Concise", tr: "Kısa ve öz"},
  {en: "Concrete", tr: "Somut"},
  {en: "Conduct", tr: "davranış"},
  {en: "Conduit", tr: "Araç"},
  {en: "Cone", tr: "Külah"},
  {en: "Confession", tr: "İtiraf"},
  {en: "Confidental", tr: "Gizli"},
  {en: "Confinement", tr: "Hapis, kapatılma"},
  {en: "confirm", tr: "onaylamak"},
  {en: "Confiscate", tr: "El koymak"},
  {en: "Conform to", tr: "Uymak"},
  {en: "Confront", tr: "Karşısına dikilmek"},
  {en: "Confusion", tr: "Karışıklık"},
  {en: "Congestion", tr: "Sıkışıklık"},
  {en: "Congregation", tr: "Cemaat"},
  {en: "Conscientious", tr: "Vicdanlı, ahlaklı"},
  {en: "consecutive", tr: "Ardışık"},
  {en: "consequence", tr: "sonuç"},
  {en: "conservative", tr: "muhafazakâr"},
  {en: "Considerable", tr: "Epeyce"},
  {en: "Considerate", tr: "Denli, düşünceli"},
  {en: "Consistent", tr: "Tutarlı"},
  {en: "conspicuous", tr: "Dikkat çekici"},
  {en: "Constitution", tr: "Anayasa"},
  {en: "Contain …self", tr: "Kendini tutmak"},
  {en: "Contemporary", tr: "Çağdaş"},
  {en: "contempt", tr: "Hor"},
  {en: "Contemptuous", tr: "Horgören"},
  {en: "Contest", tr: "Yarışma"},
  {en: "Contestant", tr: "Yarışmacı"},
  {en: "Continent", tr: "Kıta"},
  {en: "contrary", tr: "ters"},
  {en: "Contrary to popular belief", tr: "Herkesin bildiğinin aksine"},
  {en: "controversy", tr: "tartışma"},
  {en: "Convertible", tr: "Üstü açılır araba"},
  {en: "convey", tr: "götürmek"},
  {en: "Convict", tr: "Mahkum"},
  {en: "cope with", tr: "başa çıkmak"},
  {en: "Copper", tr: "Bakır"},
  {en: "Cork", tr: "Mantar"},
  {en: "Corruption", tr: "Yolsuzluk"},
  {en: "Cottage", tr: "Kulübe"},
  {en: "Council", tr: "Belediye"},
  {en: "Counselor", tr: "Danışman"},
  {en: "count on", tr: "güvenmek"},
  {en: "Courage", tr: "Cesaret"},
  {en: "Course of medication", tr: "İlaç tedavisi"},
  {en: "Court", tr: "Mahkeme, saray, kort"},
  {en: "Courteous", tr: "Nazik, kibar"},
  {en: "Cover (tv haberciliği)", tr: "Sunmak"},
  {en: "Cover up", tr: "Örtbas etmek"},
  {en: "Cowardly", tr: "Korkak"},
  {en: "Cramped", tr: "Sıkışık"},
  {en: "Crate", tr: "Kasa"},
  {en: "Crawl", tr: "Sürünmek"},
  {en: "Creature", tr: "Yaratık"},
  {en: "Creek", tr: "Dere"},
  {en: "Creepy", tr: "Korkunç, tüyler ürpertici"},
  {en: "Criticism", tr: "Eleştiri"},
  {en: "Critter", tr: "Haşere"},
  {en: "Crop", tr: "Zirai ürün, mahsül"},
  {en: "Cross", tr: "Küs"},
  {en: "Crumb", tr: "Kırıntı"},
  {en: "Crusader", tr: "Haçlı"},
  {en: "Cub", tr: "Vahşi hayvan yavrusu"},
  {en: "Cultivate", tr: "Yetiştirmek"},
  {en: "Curb", tr: "Frenlemek, etkisini azaltmak"},
  {en: "Curfew", tr: "Sokağa çıkma yasağı"},
  {en: "Curious about", tr: "Meraklı, tuhaf"},
  {en: "Curl up", tr: "Kıvrılmak, sokulmak"},
  {en: "Currency", tr: "Para kuru"},
  {en: "Curse", tr: "Lanet"},
  {en: "Curt", tr: "Kabaca kısa"},
  {en: "Curtain", tr: "Perde"},
  {en: "Cushion", tr: "Yastık, minder, tampon"},
  {en: "Custody", tr: "Alıkoyma (polis)"},
  {en: "Customs", tr: "Gümrük"},
  {en: "cut down on", tr: "azaltmak"},
  {en: "Dairy products", tr: "Süt ürünleri"},
  {en: "Damp", tr: "Hafif ıslak, nemli"},
  {en: "Dare", tr: "Cürret etmek"},
  {en: "data", tr: "veri"},
  {en: "Data (çoğul)", tr: "Veriler"},
  {en: "Datum (tekil)", tr: "Veri"},
  {en: "Dazzle", tr: "Göz kamaştırmak"},
  {en: "deal with", tr: "başa çıkmak"},
  {en: "Dealer", tr: "Satıcı"},
  {en: "Debt", tr: "Borç"},
  {en: "Debtor", tr: "Borçlu"},
  {en: "Deceit", tr: "Aldatma, yanıltma, kandırma"},
  {en: "Deceive", tr: "Kandırma"},
  {en: "Decent", tr: "Kaliteli"},
  {en: "deceptive", tr: "Aldatıcı"},
  {en: "Decisively", tr: "Nihai, sonuca götüren"},
  {en: "Decree", tr: "Mahkeme kararı"},
  {en: "deduction", tr: "Kesinti"},
  {en: "Deep down", tr: "Özünde"},
  {en: "Default on", tr: "Yükümlülüğünü yerine getirmemek"},
  {en: "defect", tr: "kusur"},
  {en: "Defendant", tr: "Sanık"},
  {en: "defer", tr: "geciktirmek"},
  {en: "Definite", tr: "Kesin"},
  {en: "defy", tr: "Defy"},
  {en: "delete", tr: "silmek"},
  {en: "Deli", tr: "Mezeci"},
  {en: "Deliberate", tr: "Kasıt"},
  {en: "Delicate", tr: "Hassas, kırılgan"},
  {en: "Delight", tr: "Keyif, zevk"},
  {en: "Delivery man", tr: "Kargocu"},
  {en: "delusion", tr: "sanrı"},
  {en: "Demand for", tr: "Talep etmek"},
  {en: "Demise", tr: "Ölüm"},
  {en: "Denim", tr: "Kot"},
  {en: "denounce", tr: "Kına"},
  {en: "Dent", tr: "Göçürmek"},
  {en: "Deny", tr: "İnkar etmek"},
  {en: "depend on", tr: "…e dayalı olmak"},
  {en: "Depict", tr: "Sergilemek, resmetmek"},
  {en: "Depreciate", tr: "Değerini azaltmak"},
  {en: "Derelict", tr: "Metruk"},
  {en: "Derision", tr: "Alay"},
  {en: "derive", tr: "türemek"},
  {en: "Derive from", tr: "Elde etmek"},
  {en: "Designate", tr: "Yetki vermek"},
  {en: "Desire", tr: "Arzu"},
  {en: "Despair", tr: "Umutsuzluk, çaresizlik"},
  {en: "destiny", tr: "kader"},
  {en: "detain", tr: "Gözaltına"},
  {en: "Detention", tr: "Alı koyma"},
  {en: "deter", tr: "alıkoymak"},
  {en: "deteriorate", tr: "bozulmak"},
  {en: "Determination", tr: "Kararlılık, azim"},
  {en: "Deterrent", tr: "Caydırıcı"},
  {en: "Devastated", tr: "Yıkılmış"},
  {en: "Develop", tr: "Gelişmek"},
  {en: "devise", tr: "tasarlamak"},
  {en: "Devolop into", tr: "Gelişip dönüşmek"},
  {en: "Devote", tr: "Adamak"},
  {en: "Devour", tr: "Tüm tüm yutmak"},
  {en: "Dialect", tr: "Lehçe"},
  {en: "Dilemma", tr: "İkilem"},
  {en: "Diligently", tr: "Gayretli bir şekilde"},
  {en: "dimensions", tr: "Boyutlar"},
  {en: "diminish", tr: "azaltmak"},
  {en: "Dip", tr: "Sos"},
  {en: "Diphthong", tr: "Çift ses"},
  {en: "Directory", tr: "Rehber"},
  {en: "Disallow", tr: "İptal etmek"},
  {en: "Disappointing", tr: "Hayal kırıklığı yaratan"},
  {en: "Disastrous", tr: "Felaketimsi"},
  {en: "Discern", tr: "Seçmek, ayırtetmek"},
  {en: "disclose", tr: "ilan etmek"},
  {en: "Disclosure", tr: "Açıklama"},
  {en: "discriminate", tr: "ayırmak"},
  {en: "Disguise", tr: "Kılık değiştirirek saklamak"},
  {en: "dismal", tr: "kasvetli"},
  {en: "Dismantle", tr: "Parçalara ayırmak"},
  {en: "dismay", tr: "dehşet"},
  {en: "Dismiss", tr: "Göndermek, dağıtmak"},
  {en: "Dispatch", tr: "Sevk etmek, göndermek"},
  {en: "dispense", tr: "dağıtmak"},
  {en: "disperse", tr: "dağıtmak"},
  {en: "Disrupt", tr: "Bozmak"},
  {en: "Dissipate", tr: "Yok etmek"},
  {en: "Distinctive", tr: "Belirgin"},
  {en: "distort", tr: "bozmak"},
  {en: "Distressed", tr: "Sıkıntılı, dertli"},
  {en: "District", tr: "Mahalle, bölge, civar"},
  {en: "diversity", tr: "Çeşitlilik"},
  {en: "divide into", tr: "bölmek"},
  {en: "Do", tr: "Kesinlikle"},
  {en: "Do the trick", tr: "İş görmek, işe yaramak"},
  {en: "Do you think", tr: "Sence"},
  {en: "doctrine", tr: "doktrin"},
  {en: "Does", tr: "Öyle mi"},
  {en: "Doesn't concern you", tr: "Seni ilgilendirmez"},
  {en: "dogmatic", tr: "dogmatik"},
  {en: "dominant", tr: "baskın"},
  {en: "donor", tr: "donör"},
  {en: "Double-glazing", tr: "Çift cam"},
  {en: "Doubt", tr: "Şüphe, kuşku"},
  {en: "Dour", tr: "Asık suratlı"},
  {en: "Down payment", tr: "Ön ödeme"},
  {en: "Down right", tr: "Düpedüz"},
  {en: "Downpour", tr: "Sağanak yağış"},
  {en: "Downside", tr: "Negatif taraf, yan"},
  {en: "Downtown", tr: "Şehir merkezi"},
  {en: "Dramatically", tr: "Çarpıcı bir şekilde"},
  {en: "drastic", tr: "Ciddi"},
  {en: "draw on", tr: "faydalanmak"},
  {en: "Drawback", tr: "Arıza, hata, kusur"},
  {en: "Dreary", tr: "Kasvetli"},
  {en: "Dressing", tr: "Sos"},
  {en: "Drop by", tr: "Çıka gelmek"},
  {en: "drop out of", tr: "…den ayrılmak"},
  {en: "Dropout", tr: "Terk"},
  {en: "Drought", tr: "Kuraklık"},
  {en: "Drowning", tr: "Boğulan"},
  {en: "dubious", tr: "şüpheli"},
  {en: "Due", tr: "Vakti gelen"},
  {en: "Dumb", tr: "Aptal"},
  {en: "Dump", tr: "Çöp, çöplük"},
  {en: "Dumping", tr: "Atılma"},
  {en: "Dusting", tr: "Toz alma"},
  {en: "Duvet", tr: "Yorgan"},
  {en: "Dynasty", tr: "Hanedanlık"},
  {en: "Eagerly", tr: "İstekle, hevesle"},
  {en: "ecstatic", tr: "Vecd"},
  {en: "Effort", tr: "Çaba"},
  {en: "Either", tr: "-de, -da"},
  {en: "elaborate", tr: "ayrıntılı"},
  {en: "elapse", tr: "geçmek"},
  {en: "Elementary school", tr: "İlk okul"},
  {en: "Elicit", tr: "Ortaya çıkarma"},
  {en: "elite", tr: "seçkin"},
  {en: "Elusive", tr: "Kaçamak, ele geçirmesi zor"},
  {en: "Embassy", tr: "Elçilik"},
  {en: "Embezzle", tr: "Zimmete para geçirmek"},
  {en: "emerge", tr: "Ortaya"},
  {en: "Eminent", tr: "Meşhur, ünlü, şöhretli"},
  {en: "Employ sb to V1", tr: "İşe almak"},
  {en: "Employee", tr: "Çalışan"},
  {en: "Employer", tr: "İş veren"},
  {en: "Enclose", tr: "Paketlemek"},
  {en: "encounter", tr: "karşılaşmak"},
  {en: "Encourage", tr: "Teşvik etmek"},
  {en: "endeavor", tr: "çaba"},
  {en: "endorse", tr: "onaylamak"},
  {en: "Endow", tr: "Bahşetmek, vermek"},
  {en: "English", tr: "Turkish"},
  {en: "Engross", tr: "Aşırı ilgisini çekmek"},
  {en: "Enthusiasm", tr: "Coşku"},
  {en: "Enticing", tr: "Cezbedici"},
  {en: "Environment", tr: "Çevre"},
  {en: "Epic", tr: "Destan"},
  {en: "Epitome of", tr: "Mükemmel örnek, ta kendisi"},
  {en: "equate", tr: "Eşit"},
  {en: "Equation", tr: "Denklem"},
  {en: "erode", tr: "Ertan"},
  {en: "Errand", tr: "Ayak işi"},
  {en: "erratic", tr: "Düzen -siz"},
  {en: "Eruption", tr: "Püskürme"},
  {en: "Escalate", tr: "Tırmanmak"},
  {en: "Espionage", tr: "Casusluk"},
  {en: "essence", tr: "cevher"},
  {en: "Euphrates", tr: "Fırat"},
  {en: "evasive", tr: "Kaçamak"},
  {en: "Eve", tr: "Arife"},
  {en: "Even", tr: "Bile, hatta"},
  {en: "Even if", tr: "Se bile"},
  {en: "Evenly", tr: "Eşit aralıklarla, düzenli aralıklarla"},
  {en: "Evict", tr: "Tahliye etmek"},
  {en: "evolve", tr: "Gelişmeye"},
  {en: "Excavation", tr: "Kazı"},
  {en: "Exceptional", tr: "Olağanüstü"},
  {en: "Excerpt", tr: "Alıntı"},
  {en: "Excessively", tr: "Aşırı"},
  {en: "Exclusive", tr: "Özel"},
  {en: "Excuse for", tr: "Mazeret"},
  {en: "Execute", tr: "İdam etmek"},
  {en: "exempt", tr: "muaf"},
  {en: "exile", tr: "sürgün"},
  {en: "exotic", tr: "Egzotik"},
  {en: "Expedition", tr: "Teknik gezi"},
  {en: "Expell", tr: "Def edilmek, def etmek, def olmak, ihraç etmek"},
  {en: "Expense", tr: "Masraf"},
  {en: "Exploit", tr: "Sömürmek"},
  {en: "Expulsion", tr: "Kovulma, okuldan ihraç"},
  {en: "Exquisite", tr: "Harika, enfes"},
  {en: "extensive", tr: "yaygın"},
  {en: "Exterior", tr: "Dış, dışa ait"},
  {en: "Extravagant", tr: "Müsrif, savurgan"},
  {en: "Fairy", tr: "Peri"},
  {en: "fall behind", tr: "geri kalmak"},
  {en: "fallacy", tr: "yanlış"},
  {en: "Famine", tr: "Açlık, kıtlık"},
  {en: "Fancy", tr: "Pahalı, lüks"},
  {en: "Far from", tr: "Şöyle dursun"},
  {en: "Far-fetched", tr: "Uyduruk"},
  {en: "Fascinate", tr: "Büyülemek, İlgisini aşırı çekmek"},
  {en: "Fault", tr: "Fay"},
  {en: "Fault line", tr: "Fay hattı"},
  {en: "Favor", tr: "(n) iyilik, (v) birinin tarafını tutmak"},
  {en: "Feast", tr: "Ziyafet"},
  {en: "Feather", tr: "Tüy"},
  {en: "Feature", tr: "(n) özellik/nitelik (v) yer vermek"},
  {en: "fed up with", tr: "bıkmak"},
  {en: "Feeble", tr: "Zayıf, cılız"},
  {en: "Fence", tr: "Çit"},
  {en: "Ferociously", tr: "Azmanca, azgın"},
  {en: "Fetch", tr: "Yakalamaca"},
  {en: "fictitious", tr: "Hayali"},
  {en: "Fident", tr: "Sadakat"},
  {en: "Field", tr: "Alan"},
  {en: "Fierce", tr: "Şiddetli"},
  {en: "Figure", tr: "Rakam, şekil"},
  {en: "figure out", tr: "çözmek"},
  {en: "Fill me in on", tr: "Anlat bana"},
  {en: "Fill the perscription", tr: "Reçeteyi hazırlamak"},
  {en: "Filthy", tr: "Leş gibi"},
  {en: "find out", tr: "anlamak, bulmak"},
  {en: "finite", tr: "sonlu"},
  {en: "Firecrack", tr: "Maytap"},
  {en: "Firework", tr: "Havai fişek"},
  {en: "Fit (mobilya)", tr: "Monte etmek"},
  {en: "Flagrant (-)", tr: "Açık, düpedüz"},
  {en: "Flair for", tr: "Yetenek"},
  {en: "Flamboyant", tr: "Gösterişli, fiyakalı, afili"},
  {en: "Flashy", tr: "Gösterişli, fiyakalı"},
  {en: "Flat tire", tr: "Patlak teker"},
  {en: "Flavor", tr: "Lezzet"},
  {en: "Flipper", tr: "Yüzgeç"},
  {en: "Float", tr: "Yüzmek"},
  {en: "Flock", tr: "Akın etmek"},
  {en: "Flour", tr: "Un"},
  {en: "Flourish", tr: "Serpilmek"},
  {en: "Flow", tr: "Akmak"},
  {en: "fluent", tr: "akıcı"},
  {en: "Fond of", tr: "Düşkün olmak, bir şeye bayılmak, çok sevmek"},
  {en: "Fool", tr: "Kandırmak"},
  {en: "For a while", tr: "Bir süre"},
  {en: "For all", tr: "Tüm … e rağmen"},
  {en: "For sale", tr: "Satılık"},
  {en: "For the time being", tr: "Bir süreliğine"},
  {en: "Foreign", tr: "Yabancı"},
  {en: "forfeit", tr: "kaybetmek"},
  {en: "Fort", tr: "Kale"},
  {en: "fortify", tr: "kuvvetlendirmek"},
  {en: "Fortify", tr: "Güçlendirmek"},
  {en: "Fortunate", tr: "Şanslı"},
  {en: "Fortune", tr: "Servet"},
  {en: "Foundation", tr: "Temel"},
  {en: "Founder", tr: "Kurucu"},
  {en: "Fountain", tr: "Çeşme"},
  {en: "Frail", tr: "Kırılgan"},
  {en: "Frantically", tr: "Çılgınlar gibi"},
  {en: "Free of sth", tr: "Arındırılmış"},
  {en: "Friction", tr: "Sürtünme"},
  {en: "Front", tr: "Cephe"},
  {en: "Frontier", tr: "Sınır, hudut"},
  {en: "frugal", tr: "tutumlu"},
  {en: "Fruit", tr: "Meyve"},
  {en: "Fulfil", tr: "Yerine getirmek"},
  {en: "Fur", tr: "Kürk"},
  {en: "Furrows", tr: "Çamurumsu oluk"},
  {en: "Furry", tr: "Tüylü"},
  {en: "Furstrate", tr: "Hüsrana uğramak"},
  {en: "Fury", tr: "Öfke"},
  {en: "Fuss", tr: "Üzerine titremek"},
  {en: "Fussiness", tr: "Pimpiriklilik"},
  {en: "futile", tr: "nafile"},
  {en: "Gambling", tr: "Kumar"},
  {en: "Gang", tr: "Çete"},
  {en: "Garage", tr: "Tamirhane"},
  {en: "Garbage can", tr: "Çöp tenekesi"},
  {en: "Gasp", tr: "Soluklanmak, nefes nefese kalmak"},
  {en: "Gauge", tr: "Gösterge"},
  {en: "Geld", tr: "İğdiş etmek"},
  {en: "Generous", tr: "Cömert"},
  {en: "Genres", tr: "Tür (Kitap, film)"},
  {en: "Genuinely", tr: "Gerçekten"},
  {en: "gesture", tr: "jest"},
  {en: "Get a raise", tr: "Zam almak"},
  {en: "Get along", tr: "Geçinmek"},
  {en: "Get back at", tr: "İntikam almak"},
  {en: "Get down on", tr: "Moralini bozmak"},
  {en: "Get hold of", tr: "Ele geçirmek, elde etmek"},
  {en: "Get off with", tr: "İle kurtulmak"},
  {en: "get over", tr: "atlatmak"},
  {en: "get rid of", tr: "…den kurtulmak"},
  {en: "Get the shot", tr: "Aşı olmak"},
  {en: "Get through", tr: "Halletmek, üstesinden gelmek"},
  {en: "give away", tr: "sırrı ifşa etmek"},
  {en: "give birth to", tr: "…e yol açmak"},
  {en: "give in", tr: "teslim olmak"},
  {en: "give up", tr: "vazgeçmek"},
  {en: "Giveaway", tr: "Beleş verilen ürün"},
  {en: "Glacier", tr: "Buzul"},
  {en: "Glare at", tr: "Öfkeyle bakmak"},
  {en: "Glitter", tr: "Simli"},
  {en: "Glow", tr: "Parlamak"},
  {en: "Go against", tr: "Aykırı olmak"},
  {en: "Go along with = accept", tr: "Kabul etmek"},
  {en: "go down with", tr: "hastalanmak"},
  {en: "go in for", tr: "…e katılmak"},
  {en: "Go off", tr: "Alarmın çalması"},
  {en: "go on", tr: "devam etmek"},
  {en: "go through", tr: "başına gelmek"},
  {en: "Go too far", tr: "Aşırıya kaçmak"},
  {en: "Go up = increase", tr: "Yukarı git = artım"},
  {en: "Gold-digger", tr: "Para avcısı"},
  {en: "Goose bump", tr: "Tüylerin diken diken olması"},
  {en: "Gorgeus", tr: "Mükemmel"},
  {en: "Grade school", tr: "İlk okul"},
  {en: "Grain", tr: "Tanecik"},
  {en: "Grandly", tr: "Görkemli"},
  {en: "Grasp", tr: "Sıkıca kavramak"},
  {en: "Gratitude for", tr: "Minnettarlık, sükran"},
  {en: "Gravel", tr: "Çakıl"},
  {en: "Gravy", tr: "Et suyu"},
  {en: "Grease", tr: "Yağ"},
  {en: "Greedy", tr: "Açgözlü"},
  {en: "Greeting", tr: "Karşılama"},
  {en: "Grin", tr: "Sırıtmak"},
  {en: "Groan", tr: "Homurdanmak"},
  {en: "Groom", tr: "Damat"},
  {en: "Gross", tr: "İğrenç"},
  {en: "Groundbreaking", tr: "Çığır açan"},
  {en: "Growling", tr: "Hırlama"},
  {en: "gruesome", tr: "korkunç"},
  {en: "gullible", tr: "saf"},
  {en: "Gulp down", tr: "Fon dip"},
  {en: "Gum", tr: "1)Diş eti 2)Sakız"},
  {en: "Hail", tr: "Dolu yağması"},
  {en: "Half", tr: "Yarım"},
  {en: "Hallway", tr: "Koridor"},
  {en: "Hammer", tr: "Çekiç"},
  {en: "Hammock", tr: "Hamak"},
  {en: "Hand", tr: "Teslim etmek, elden vermek"},
  {en: "hand down", tr: "devretmek"},
  {en: "hand in", tr: "teslim etmek"},
  {en: "Hand over", tr: "Teslim etmek"},
  {en: "Handcuffs", tr: "Kelepçe"},
  {en: "Handkerchief", tr: "Mendil"},
  {en: "Handle", tr: "Kucağa almak"},
  {en: "Hangover", tr: "Akşamdan kalma"},
  {en: "harass", tr: "Taciz"},
  {en: "Hare", tr: "Büyük tavşan"},
  {en: "Harsh", tr: "Sert, haşin"},
  {en: "Hatching", tr: "Kulukça"},
  {en: "Haunt", tr: "Musallat olmak"},
  {en: "Haunted", tr: "Perili"},
  {en: "Have high hope", tr: "Umudu yüksek olmak"},
  {en: "Have one’s fair share", tr: "Payına düşeni almak"},
  {en: "Have the nerve", tr: "Cüret etmek"},
  {en: "Have to do with", tr: "İle alakalı olmak"},
  {en: "Have trouble ving", tr: "Bir iş yapmakta zorlanma"},
  {en: "Have trouble with sb/sth", tr: "Sorun yaşama"},
  {en: "Hay fever", tr: "Saman nezlesi"},
  {en: "head for", tr: "…e yönelmek"},
  {en: "Head over heels in love", tr: "Sırılsıklam aşık"},
  {en: "Head toward", tr: "Topuklamak"},
  {en: "Head-on", tr: "Bodosloma"},
  {en: "Headquarter", tr: "Merkez"},
  {en: "Headstrong", tr: "İnatçı"},
  {en: "Hearing", tr: "Duruşma"},
  {en: "Heed", tr: "Kulak asmak"},
  {en: "Heir", tr: "Varis"},
  {en: "Helping", tr: "Porsiyon"},
  {en: "Helpless", tr: "Çaresiz"},
  {en: "Herculean = huge", tr: "Aşırı kocaman, devasa"},
  {en: "Hereby", tr: "Bu vesileyle"},
  {en: "Hesitate", tr: "Tereddüt etmek"},
  {en: "Highschool dropout", tr: "Lise terk"},
  {en: "Hinder", tr: "Engellemek, mani olmak"},
  {en: "Hinge", tr: "Kapı menteşesi"},
  {en: "hinge on", tr: "…e dayalı olmak"},
  {en: "Hint at", tr: "İma etmek"},
  {en: "Hiss", tr: "Tıslamak"},
  {en: "Hive", tr: "Kovan"},
  {en: "Hollow", tr: "İçi boş"},
  {en: "Hoop", tr: "Halka"},
  {en: "Hop", tr: "Zıplamak"},
  {en: "Horizon", tr: "Ufuk çizgisi"},
  {en: "Hose", tr: "Boru"},
  {en: "Hostage", tr: "Rehine"},
  {en: "Hostile", tr: "Düşmanca, hasmane"},
  {en: "Hound", tr: "Tazı"},
  {en: "However", tr: "Ama"},
  {en: "Humans (bilimsel)", tr: "İnsanlar"},
  {en: "Humid", tr: "Rutibetli, nemli"},
  {en: "Humor", tr: "Komedi"},
  {en: "Hurl", tr: "Fırlatmak"},
  {en: "Hurricane", tr: "Kasırga"},
  {en: "hypocrite", tr: "ikiyüzlü"},
  {en: "I can’t understand the fun of", tr: "….ne eğlencesi var"},
  {en: "I figüre that = I think that", tr: "Sanırım = Bence"},
  {en: "Idle", tr: "Aylak"},
  {en: "Idolize", tr: "Tanrılaştırmak"},
  {en: "Illiterate", tr: "Okur yazar değil"},
  {en: "Illuminate", tr: "Aydınlatmak"},
  {en: "Immeasurable", tr: "Paha biçilmez"},
  {en: "Immensely", tr: "Devasa"},
  {en: "Impartial", tr: "Tarafsız"},
  {en: "Implausible", tr: "Mantıksız, saçma"},
  {en: "Implication", tr: "İma"},
  {en: "Imply", tr: "İma etmek"},
  {en: "Impress", tr: "Etkilemek"},
  {en: "Impromptu", tr: "Doğaçlamak"},
  {en: "Improper", tr: "Uygunsuz"},
  {en: "Improvising", tr: "Doğaçlama"},
  {en: "In a bad mood", tr: "Huysuz, aksi"},
  {en: "In a fit of anger", tr: "Öfke kriziyle"},
  {en: "In accordance with", tr: "-e uygun olarak"},
  {en: "In an attempt to", tr: "Mek mak için"},
  {en: "In good shape", tr: "Formda"},
  {en: "In no time", tr: "Çok geçmeden"},
  {en: "In one go", tr: "Tek seferde"},
  {en: "In part", tr: "Kısmen"},
  {en: "In the act", tr: "Suçüstü"},
  {en: "In the face of", tr: "Karşısında"},
  {en: "In the future", tr: "Gelecekte"},
  {en: "In time", tr: "Zamanında (durum için)"},
  {en: "Inadequately", tr: "Yetersiz bir şekilde"},
  {en: "Inadvertantly", tr: "İstemeden"},
  {en: "Incentive-based", tr: "Teşvik tabanlı"},
  {en: "Inclinatiton to V1", tr: "Eğilim"},
  {en: "Income tax", tr: "Gelir vergisi"},
  {en: "Inconvenience", tr: "Rahatsızlık"},
  {en: "Inconvenient", tr: "Uygunsuz"},
  {en: "Increasingly", tr: "Giderek"},
  {en: "Indigenous", tr: "Yerli"},
  {en: "Indispensable", tr: "Vazgeçilmez, zaruri"},
  {en: "Industrious", tr: "Çalışkan"},
  {en: "Inept", tr: "Beceriksiz"},
  {en: "Inequity", tr: "Adaletsizik, haksızlık"},
  {en: "Infest", tr: "İstila etmek"},
  {en: "Infinite", tr: "Sınırsız"},
  {en: "Infirmity", tr: "Zayıflık, acizlik, sakatlık"},
  {en: "Inflict", tr: "Neden olmak, (zarar) vermek"},
  {en: "Inflict damage on", tr: "Zarar vermek"},
  {en: "Infringe on", tr: "Hakkını yemek"},
  {en: "Ingenious", tr: "Hünerli, yaratıcı"},
  {en: "Inhibit", tr: "Engellemek"},
  {en: "Inhibitor", tr: "Doğum kontrol hapı"},
  {en: "Inmate", tr: "Mahkum"},
  {en: "Innate", tr: "Doğuştan"},
  {en: "Inning", tr: "Çeyrek"},
  {en: "Innovative", tr: "Yenilikçi"},
  {en: "Inoffensive", tr: "Gücendirmeyen"},
  {en: "Insight into", tr: "Anlayış"},
  {en: "Insole", tr: "Taban"},
  {en: "Inspector", tr: "Müfettiş"},
  {en: "Instance", tr: "Örnek"},
  {en: "Instantaneous", tr: "Anlık"},
  {en: "Instantly", tr: "Anında"},
  {en: "Instill in", tr: "Aşılamak"},
  {en: "Insult", tr: "Aşağlamak"},
  {en: "Integrity", tr: "Namus, dürüstlük"},
  {en: "Intelligence", tr: "Haber alma, istihbarat"},
  {en: "Intensly", tr: "Çok"},
  {en: "Intention", tr: "Niyet"},
  {en: "Intercede", tr: "Araya girmek, aracı olmak"},
  {en: "Interfere", tr: "Müdahale"},
  {en: "Interpretation", tr: "Yorumlama, açıklama"},
  {en: "Intervarsity", tr: "Üniversiteler arası"},
  {en: "Intervene", tr: "Müdahale etmek, karışmak"},
  {en: "Intricate", tr: "Karmaşık"},
  {en: "Intrigue", tr: "Merak uyandırmak, Dikkatini çekmek"},
  {en: "Intriguing", tr: "İlgi çekici"},
  {en: "Invest in", tr: "Yatırım yapmak"},
  {en: "Irate", tr: "Kızgın, sinirli, öfkeli"},
  {en: "Irrational", tr: "Mantık dışı"},
  {en: "Irrevocable", tr: "Geri dönüşümsüz"},
  {en: "Is that", tr: "Şudur (ki)"},
  {en: "Is to", tr: "-mektir, -maktır"},
  {en: "Isolate", tr: "Ayırmak"},
  {en: "It is so", tr: "Durum böyle"},
  {en: "Ivory", tr: "Fildişi"},
  {en: "Ivy", tr: "Sarmaşık"},
  {en: "idealistic", tr: "Idealist"},
  {en: "illuminate", tr: "aydınlatmak"},
  {en: "illusion", tr: "yanılsama"},
  {en: "immunity", tr: "dokunulmazlık"},
  {en: "impact", tr: "etki"},
  {en: "impair", tr: "bozmak"},
  {en: "impartial", tr: "tarafsız"},
  {en: "imply", tr: "gerektirmek"},
  {en: "impose", tr: "Empoze"},
  {en: "impulsive", tr: "Dürtüsel"},
  {en: "indifferent", tr: "ilgisiz"},
  {en: "indignant", tr: "Öfkeli"},
  {en: "indulgent", tr: "Hoşgörülü"},
  {en: "inept", tr: "beceriksiz"},
  {en: "inevitable", tr: "kaçınılmaz"},
  {en: "infer", tr: "Gerçekleştirip"},
  {en: "infinite", tr: "sonsuz"},
  {en: "inflict", tr: "Vermek"},
  {en: "ingenious", tr: "zeki"},
  {en: "inhibit", tr: "tutmak"},
  {en: "initiate", tr: "başlatmak"},
  {en: "innate", tr: "Doğuş -tan gelen"},
  {en: "integrity", tr: "bütünlük"},
  {en: "intervene", tr: "Müdahale"},
  {en: "isolate", tr: "ayırmak"},
  {en: "Janitor", tr: "Kapıcı"},
  {en: "Jerk", tr: "Ahmak"},
  {en: "Job opening", tr: "Boş kadro"},
  {en: "Jolly", tr: "Neşeli"},
  {en: "Jolt", tr: "Sarsmak"},
  {en: "Jot down", tr: "Hızlı hızlı not etmek"},
  {en: "Jumble", tr: "Yığın"},
  {en: "Jumper", tr: "Kazak"},
  {en: "Junk", tr: "Ivır zıvır"},
  {en: "Jurisdiction", tr: "Yetki alanı"},
  {en: "Juror", tr: "Jüri üyesi"},
  {en: "Just as", tr: "Tam iken, tıpkı gibi"},
  {en: "Just in case", tr: "Ne olur ne olmaz diye"},
  {en: "Keel over", tr: "Aniden yığılmak, fenalaşmak"},
  {en: "Keenness", tr: "Keskinlik"},
  {en: "keep off", tr: "uzak durmak"},
  {en: "keep on", tr: "devam etmek"},
  {en: "keep pace with", tr: "yetişmek"},
  {en: "Keep up the hope", tr: "Umudu sürdür"},
  {en: "keep up with", tr: "yetişmek"},
  {en: "Kennel", tr: "Köpek kulübesi"},
  {en: "Kneel", tr: "Dizinin üstüne çökmek"},
  {en: "Knock down", tr: "Yıkmak"},
  {en: "Labor", tr: "Çalışma"},
  {en: "lament", tr: "ağlamak"},
  {en: "Landscape", tr: "Manzara"},
  {en: "Lane", tr: "Şerit"},
  {en: "Language", tr: "Dil"},
  {en: "Late", tr: "Rahmetli"},
  {en: "Latitude", tr: "Enlem"},
  {en: "Lawn", tr: "Çim"},
  {en: "Lay off", tr: "İşten çıkarmak"},
  {en: "lead to", tr: "neden olmak"},
  {en: "Leaflet", tr: "Broşür"},
  {en: "Lean", tr: "Eğilmek"},
  {en: "Leap", tr: "Atlamak, sıçramak, hoplamak"},
  {en: "Leash", tr: "Tasma"},
  {en: "Ledge", tr: "Çıkıntı"},
  {en: "Leech", tr: "Sülük"},
  {en: "Leftovers", tr: "Geriye kalanlar"},
  {en: "Legislation", tr: "Yasama"},
  {en: "legitimate", tr: "meşru"},
  {en: "Leisure", tr: "Boş vakit, boş zaman"},
  {en: "Lemon", tr: "Çürük mal"},
  {en: "Lend", tr: "Ödünç vermek"},
  {en: "lenient", tr: "Yumuşak"},
  {en: "Let sb know", tr: "Haber vermek"},
  {en: "Let us know", tr: "Haber vermek"},
  {en: "lethal", tr: "Öldürücü"},
  {en: "liable", tr: "Sorumlu"},
  {en: "Libel", tr: "İftira, iftira atmak"},
  {en: "liberal", tr: "liberal"},
  {en: "Life span", tr: "Ömür süresi"},
  {en: "Lily", tr: "Zambak"},
  {en: "literally", tr: "Gerçek -ten"},
  {en: "Literate", tr: "Okur yazar"},
  {en: "Litter", tr: "Çöp"},
  {en: "Lizard", tr: "Kertenkele"},
  {en: "Loaf", tr: "Ekmek"},
  {en: "Loan", tr: "Kredi, borç"},
  {en: "Loaves", tr: "Ekmekler"},
  {en: "Lobster", tr: "Istakoz"},
  {en: "Log", tr: "Kereste, kütük"},
  {en: "look after", tr: "göz kulak olmak"},
  {en: "look for", tr: "aramak"},
  {en: "look into", tr: "araştırmak"},
  {en: "Loose", tr: "Gevşeyen, sallanan"},
  {en: "Loosely", tr: "Öylesine"},
  {en: "Lot", tr: "Arsa"},
  {en: "Luddite", tr: "Teknoloji özürlü, düşmanı"},
  {en: "lure", tr: "cezbetmek"},
  {en: "Lure", tr: "Cezbetmek"},
  {en: "Mad", tr: "Deli, çılgın, çok sevme, öfkeli"},
  {en: "Main", tr: "Depo"},
  {en: "Major", tr: "Büyük ve önemli"},
  {en: "make do with", tr: "ile yetinmek"},
  {en: "Make for", tr: "Barındırmak"},
  {en: "Make greater", tr: "Artırmak"},
  {en: "Make it to", tr: "Yetişmek"},
  {en: "make out", tr: "çözmek"},
  {en: "make up", tr: "oluşturmak"},
  {en: "make up for", tr: "telafi etmek"},
  {en: "make use of", tr: "faydalanmak"},
  {en: "malicious", tr: "kötü niyetli"},
  {en: "Maneuvering", tr: "Manevra"},
  {en: "mania", tr: "Mani"},
  {en: "Mania (n)", tr: "Düşkün"},
  {en: "Manner", tr: "Tarz, tavır"},
  {en: "Manor", tr: "Malikane"},
  {en: "Mansion", tr: "Konak"},
  {en: "Marble", tr: "Mermer, bilye"},
  {en: "Mark", tr: "Damga"},
  {en: "Marketing manager", tr: "Pazarlama müdürü"},
  {en: "Massacre", tr: "Katliam"},
  {en: "Maverick", tr: "Sürüden ayrılan dana, farklı davranan kişi"},
  {en: "Meadow", tr: "Çayır"},
  {en: "Mean", tr: "Edepsiz"},
  {en: "Means", tr: "Yol(ler), yöntem(ler)"},
  {en: "mediocre", tr: "vasat"},
  {en: "menace", tr: "Tehdit"},
  {en: "Menace to", tr: "Tehdit"},
  {en: "Mend", tr: "Tamir etmek"},
  {en: "Merely", tr: "Sadece"},
  {en: "Mesh", tr: "Ağ"},
  {en: "Mess", tr: "Pislik"},
  {en: "Messy", tr: "Dağınık"},
  {en: "Meteorite", tr: "Gök taşı"},
  {en: "Methodical", tr: "Düzenli, tertipli"},
  {en: "Metloaf", tr: "Köfte"},
  {en: "Might", tr: "-e bilir"},
  {en: "Migrate", tr: "Göç etmek"},
  {en: "Minuscule", tr: "Çok küçük"},
  {en: "Mischief", tr: "Yaramazlık"},
  {en: "Miserable", tr: "Acınası"},
  {en: "miserly", tr: "cimri"},
  {en: "Misplace", tr: "Koyduğu yeri unutmak"},
  {en: "Mist", tr: "Sis"},
  {en: "Moan", tr: "Yakınmak"},
  {en: "Mob (v)\n(n)", tr: "Hücum etmek\nKalabalık"},
  {en: "moderate", tr: "ılımlı"},
  {en: "Moisture", tr: "Nem"},
  {en: "Moldy", tr: "Küflü"},
  {en: "Monotonous", tr: "Monoton"},
  {en: "Monument", tr: "Anıt"},
  {en: "Moral", tr: "Ahlak"},
  {en: "morale", tr: "Moral"},
  {en: "morbid", tr: "hastalıklı"},
  {en: "Morbid", tr: "Ölümcül"},
  {en: "More than ever", tr: "Eskisinden daha fazla"},
  {en: "Mountain range", tr: "Dağ"},
  {en: "Mountainous", tr: "Dağlık"},
  {en: "Mover", tr: "Hammal"},
  {en: "Mow", tr: "Çim biçmek"},
  {en: "Muddy", tr: "Çamurlu"},
  {en: "Mugging", tr: "Gasp"},
  {en: "Mule", tr: "Katır"},
  {en: "Murmuring", tr: "Mırıldanmak"},
  {en: "Museum", tr: "Müze"},
  {en: "MVP (most valuable player)", tr: "MVP (en değerli oyuncu)"},
  {en: "Nagging", tr: "Dırdır"},
  {en: "naive", tr: "saf"},
  {en: "name after", tr: "isim vermek"},
  {en: "Nasty", tr: "Edepsiz, pis"},
  {en: "Native", tr: "Yerli"},
  {en: "Naughty", tr: "Yaramazlık"},
  {en: "Naval", tr: "Deniz (kuvvetleri)"},
  {en: "Neat", tr: "Derli toplu"},
  {en: "Neatly", tr: "Düzgün şekilde"},
  {en: "Nefarious", tr: "Hain"},
  {en: "Negotiator", tr: "Müzakereci"},
  {en: "Neighborhood", tr: "Mahalle"},
  {en: "Nest", tr: "Yuva"},
  {en: "Nesting", tr: "Yuva yapma"},
  {en: "Never less and never more", tr: "Ne eksik ne fazla"},
  {en: "Nightingale", tr: "Bülbül"},
  {en: "No longer", tr: "Artık değil"},
  {en: "No matter", tr: "Fark etmez"},
  {en: "Nodding off", tr: "Uyuklamak"},
  {en: "Nominal fine", tr: "Hafif para cezası"},
  {en: "Nook = hole", tr: "Delik"},
  {en: "Nose up in the air", tr: "Burnu havada"},
  {en: "nostalgia", tr: "hasret"},
  {en: "Not long ago", tr: "Çok da uzun süre geçmeden"},
  {en: "notable", tr: "dikkate değer"},
  {en: "Nothing to do with", tr: "İle alakası yok"},
  {en: "Novel", tr: "Yeni, roman"},
  {en: "novice", tr: "Acemi"},
  {en: "Numb", tr: "Uyuşmuş, uyuşturmak"},
  {en: "Number", tr: "Sayısı olmak"},
  {en: "Nun", tr: "Rahibe"},
  {en: "Oak", tr: "Meşe"},
  {en: "Obnoxious", tr: "Sevimsiz"},
  {en: "Obselete", tr: "Demode, modası geçmiş"},
  {en: "obsession", tr: "Saplantı"},
  {en: "obstacle", tr: "engel"},
  {en: "obstinate", tr: "inatçı"},
  {en: "Occasion", tr: "Durum"},
  {en: "Odd", tr: "Tek rakam"},
  {en: "Of all", tr: "Tüm … arasında"},
  {en: "Of my own", tr: "Kendime ait"},
  {en: "Off", tr: "Aşağı"},
  {en: "Offender", tr: "Suç işleyen"},
  {en: "On earth", tr: "Allah aşkına"},
  {en: "On good terms", tr: "Aramız iyi"},
  {en: "On sale", tr: "İndirimde"},
  {en: "On the river bank", tr: "Irmak kenarında"},
  {en: "On time", tr: "Zamanında (belirli zaman)"},
  {en: "Once in a while = sometimes", tr: "Ara sıra = bazen"},
  {en: "On-demand", tr: "Anında"},
  {en: "One’s", tr: "Kişinin"},
  {en: "Only", tr: "Sadece"},
  {en: "Only if", tr: "Ancak … -se,-sa"},
  {en: "Onset", tr: "Ortaya çıkmak"},
  {en: "Opinionated", tr: "Tek yönlü bakan"},
  {en: "Opposition", tr: "Başkaldırı"},
  {en: "optimist", tr: "optimist"},
  {en: "option", tr: "seçenek"},
  {en: "Or so", tr: "Veya civarı"},
  {en: "Oratory", tr: "Nutuk"},
  {en: "ordeal", tr: "çile"},
  {en: "Ornament", tr: "Süs eşyaları"},
  {en: "Ostentatious", tr: "Afili, gösterişli, şatafatlı"},
  {en: "Outbreak of", tr: "…nın patlak vermesi"},
  {en: "Outer space", tr: "Atmosfer dışı uzay"},
  {en: "Outgrow", tr: "Büyüdükçe unutmak"},
  {en: "Outrage", tr: "Hiddet, öfke"},
  {en: "overt", tr: "Açık"},
  {en: "Owl", tr: "Baykuş"},
  {en: "Oyster", tr: "İstiridye"},
  {en: "Pact on", tr: "Antlaşma"},
  {en: "Pages", tr: "Sayfalar"},
  {en: "Pain in the neck", tr: "Boyun ağrısı"},
  {en: "Pair", tr: "Çift"},
  {en: "Pale", tr: "Solgun"},
  {en: "Pan", tr: "Tava"},
  {en: "Parade", tr: "Geçit töreni"},
  {en: "parallel", tr: "koşut"},
  {en: "Parsley", tr: "Maydanoz"},
  {en: "Pass along", tr: "İletmek"},
  {en: "pass away", tr: "ölmek"},
  {en: "Passerine", tr: "Ötücü kuş"},
  {en: "Passionate", tr: "Tutkulu, ateşli"},
  {en: "passive", tr: "pasif"},
  {en: "Pat", tr: "Sıvazlamak"},
  {en: "Pathetic", tr: "Acınası"},
  {en: "Patio", tr: "Teras"},
  {en: "patron", tr: "müşteri"},
  {en: "Pay a reasonable price for", tr: "Makul fiyat ödemek"},
  {en: "pay off", tr: "işe yaramak"},
  {en: "Pear", tr: "Armut"},
  {en: "Peas", tr: "Bezelye, leblebi"},
  {en: "Peat", tr: "Turba (bataklık kömürü)"},
  {en: "Peninsula", tr: "Yarım ada"},
  {en: "Pension", tr: "Emekli maaşı"},
  {en: "Pensioner", tr: "Emekli"},
  {en: "Peoples", tr: "Halklar"},
  {en: "Peoples (sosyoloji, psikoloji)", tr: "İnsanlar"},
  {en: "Pep talk", tr: "Gaz veren konuşma"},
  {en: "perceptive", tr: "Algı"},
  {en: "Perch", tr: "Tünemek"},
  {en: "Perennial", tr: "Yıl boyu süren"},
  {en: "Perjury", tr: "Yalan yere yemin"},
  {en: "Perseverance", tr: "Azim"},
  {en: "Persevere", tr: "Azmetmek"},
  {en: "persistent", tr: "Kalıcı"},
  {en: "pessimist", tr: "kötümser"},
  {en: "Pharaoh", tr: "Firavun"},
  {en: "phobia", tr: "fobi"},
  {en: "Picket", tr: "Görevde gözcülük yapmak"},
  {en: "Pickle", tr: "Turşu"},
  {en: "Pickpocket", tr: "Yan kesici"},
  {en: "Pile", tr: "Yığın (Çamaşır)"},
  {en: "Pine", tr: "Çam"},
  {en: "Pioneer", tr: "Öncü, öncülük etmek"},
  {en: "Pipeline", tr: "Boru hattı"},
  {en: "Pitch", tr: "1. Atmak (örn: top) 2. Kurmak"},
  {en: "Pitch in", tr: "Elini taşın altına koymak"},
  {en: "Plain", tr: "1)Ova 2)Açık"},
  {en: "Plant", tr: "Tesis"},
  {en: "plausible", tr: "Makul"},
  {en: "Playground", tr: "Park"},
  {en: "Plead", tr: "Mahkemede savunmak, istekde bulunmak"},
  {en: "Pleasent", tr: "Hoş, sevimli"},
  {en: "Pleasure", tr: "Zevk"},
  {en: "Plenty", tr: "Çok, bol"},
  {en: "Pliable", tr: "Şekil verilebilir"},
  {en: "Plot", tr: "Komplo"},
  {en: "Plumber", tr: "Su tesisatçısı"},
  {en: "Plump", tr: "Tombul"},
  {en: "Plunge", tr: "Hızla düşmek, dalmak"},
  {en: "Poet", tr: "Şair"},
  {en: "point out", tr: "göstermek"},
  {en: "Poke", tr: "Dürtmek"},
  {en: "Pole", tr: "Olta"},
  {en: "Pond", tr: "Gölet"},
  {en: "Pony", tr: "Midilli"},
  {en: "Popp", tr: "Şişirmek"},
  {en: "Popular", tr: "Sevilen beğenilen"},
  {en: "Portland", tr: "Portland"},
  {en: "Possession", tr: "1) Kişisel eşya 2) Bulundurmak"},
  {en: "Post", tr: "Kazık, direk"},
  {en: "Potted", tr: "Saksı"},
  {en: "Pounding headache", tr: "Zonklayıcı baş ağrısı"},
  {en: "Pour down", tr: "Dök"},
  {en: "Poverty", tr: "Yoksulluk"},
  {en: "Power outage", tr: "Elektrik kesintisi"},
  {en: "Prairie", tr: "Ova"},
  {en: "Preacher", tr: "Vaiz"},
  {en: "Precarious", tr: "Tehlikeli"},
  {en: "Precipitation", tr: "Yağış, çökelti"},
  {en: "Prefer to v1…Than (to) V1", tr: "V1'i tercih ediyorum... V1'den daha"},
  {en: "Prefer Ving…to Ving", tr: "Ving'i tercih ederim... Ving'e"},
  {en: "Premise", tr: "İşyeri sahası"},
  {en: "Pressing", tr: "Acil çözüm bekleyen"},
  {en: "pretense", tr: "bahane"},
  {en: "Pretzel", tr: "Çubuk kraker"},
  {en: "prevail", tr: "Hakim"},
  {en: "Preview", tr: "Fragman"},
  {en: "Prey", tr: "Av"},
  {en: "Priceless", tr: "Paha biçilmez"},
  {en: "Pride", tr: "Gurur"},
  {en: "Principal", tr: "Müdür"},
  {en: "procrastinate", tr: "gecikme"},
  {en: "Proficient(ly)", tr: "Usta(ca)"},
  {en: "profound", tr: "derin"},
  {en: "prolong", tr: "Prolong"},
  {en: "prominent", tr: "önde gelen"},
  {en: "Promotion", tr: "Terfi"},
  {en: "Prompt", tr: "Neden olmak"},
  {en: "propaganda", tr: "propaganda"},
  {en: "propel", tr: "It -mek"},
  {en: "Properly", tr: "Adam akıllı"},
  {en: "Property", tr: "Arazi, mülk, emlak"},
  {en: "Proposal", tr: "Öneri, teklif"},
  {en: "Proposterous", tr: "Gülünç, komik"},
  {en: "Prosecute", tr: "Hakkında dava açmak"},
  {en: "Prosecutor", tr: "Savcı"},
  {en: "prospects", tr: "Potansiyel"},
  {en: "Prospects", tr: "Ümit, beklenti, olasılık"},
  {en: "Prove to", tr: "Kanıtlamak"},
  {en: "Province", tr: "Vilayet, il"},
  {en: "provoke", tr: "dürtmek"},
  {en: "prudent", tr: "tutumlu"},
  {en: "Psyches", tr: "Ruh hali"},
  {en: "Publicity", tr: "Halk ilgisi"},
  {en: "Puddle", tr: "Su birikintisi"},
  {en: "Puff up", tr: "Şişirmek"},
  {en: "pull through", tr: "iyileşmek"},
  {en: "Pulp", tr: "Kağıt hamuru"},
  {en: "Punchline", tr: "Bitirici cümle"},
  {en: "Purse", tr: "Küçük kadın çantası"},
  {en: "Push away", tr: "İtip uzaklaştırmak"},
  {en: "put aside", tr: "para biriktirmek"},
  {en: "put forth", tr: "ileri sürmek"},
  {en: "put forward", tr: "ileri sürmek"},
  {en: "put off", tr: "ertelemek"},
  {en: "Put on", tr: "Sahnelemek"},
  {en: "put out", tr: "söndürmek"},
  {en: "put up with", tr: "katlanmak"},
  {en: "query", tr: "sorgu"},
  {en: "Quiet", tr: "Sessiz"},
  {en: "Quilt", tr: "Yorgan"},
  {en: "Quirk", tr: "Tuhaf, garip"},
  {en: "Quite a/an tekil isim", tr: "Muhteşem"},
  {en: "Quodb", tr: "Quodb"},
  {en: "Quotation", tr: "Fiyat teklifi"},
  {en: "Racetrack", tr: "Yarış pisti"},
  {en: "Radiance", tr: "Parlama"},
  {en: "radical", tr: "Radikal"},
  {en: "Raise", tr: "Artırmak, toplamak (para)"},
  {en: "Raise Money", tr: "Para toplamak"},
  {en: "Rake", tr: "Sonbahar temizliği"},
  {en: "Rape", tr: "Tecavüz"},
  {en: "Rapid = swift", tr: "Hızlı = hızlı"},
  {en: "rational", tr: "rasyonel"},
  {en: "Readily", tr: "Kolayca"},
  {en: "Rear", tr: "Arka taraf"},
  {en: "Reassuringly", tr: "Kesinlikle"},
  {en: "recede", tr: "geri çekilmek"},
  {en: "Receipt", tr: "Fiş, fatura, ödendi makbuzu"},
  {en: "Recipe", tr: "Tarif"},
  {en: "recipient", tr: "alıcı"},
  {en: "reciprocate", tr: "Karşılık"},
  {en: "Recreation", tr: "Boş zaman değerlendirme"},
  {en: "recur", tr: "Nüksetme"},
  {en: "Recurring", tr: "Nüks eden"},
  {en: "refer to", tr: "anlamına gelmek"},
  {en: "refrain", tr: "Kaçınmak"},
  {en: "refrain from", tr: "kaçınmak"},
  {en: "refuge", tr: "sığınak"},
  {en: "refute", tr: "reddetmek"},
  {en: "Regret", tr: "Pişman olmak"},
  {en: "Rehears", tr: "Prova yapmak"},
  {en: "Rehearsal", tr: "Prova"},
  {en: "Rein", tr: "Dizgin"},
  {en: "reinforce", tr: "kuvvetlendirmek"},
  {en: "Reinforce", tr: "Güçlendirmek, kuvvetlendirmek"},
  {en: "Rejoice", tr: "Sevinmek"},
  {en: "Relative", tr: "Akraba"},
  {en: "relevant", tr: "alakalı"},
  {en: "Relief", tr: "Rahatlama"},
  {en: "Relieve", tr: "Rahatlama"},
  {en: "Relinquish", tr: "Vazgeçmek"},
  {en: "rely on", tr: "…e bel bağlamak"},
  {en: "Remarkably", tr: "Dikkat çekici bir şekilde"},
  {en: "Remedy", tr: "İlaç"},
  {en: "Remind", tr: "Hatırlatmak"},
  {en: "reminisce", tr: "Hatırla -dınız"},
  {en: "Reminisce", tr: "Hatırlayıp hk konuşmak, yad etmek"},
  {en: "remorse", tr: "Vicdan azabı"},
  {en: "Renewable", tr: "Yenilenebilir"},
  {en: "Renovation", tr: "Tadilat"},
  {en: "Replacement", tr: "Yedek"},
  {en: "Report card", tr: "Karne"},
  {en: "reprimand", tr: "azarlamak"},
  {en: "Reputation", tr: "Şöhret"},
  {en: "Require = 1) need, 2) demand", tr: "1.     İhtiyaç duymak 2.     Talep etmek, istemek"},
  {en: "Require sb to V1", tr: "Talep etmek"},
  {en: "Residential", tr: "Yerleşim alanı"},
  {en: "Resilient", tr: "Çabuk iyileşen, toparlanan"},
  {en: "Resolution", tr: "Karar"},
  {en: "Resolve", tr: "Karar vermek, karar almak"},
  {en: "Resort", tr: "Tatil beldesi"},
  {en: "rest on", tr: "…e dayalı olmak"},
  {en: "restrain", tr: "tutmak"},
  {en: "Restriction on", tr: "Kısıtlama"},
  {en: "result in", tr: "ile sonuçlanmak"},
  {en: "retain", tr: "tutmak"},
  {en: "retort", tr: "Imbik"},
  {en: "retrieve", tr: "Almak"},
  {en: "Revelation", tr: "Açığa çıkmak"},
  {en: "Revenue", tr: "Ülkenin geliri"},
  {en: "revert", tr: "Geri dönmek"},
  {en: "Revive", tr: "Canlandırmak"},
  {en: "revoke", tr: "İptal etme"},
  {en: "Revolve", tr: "Dönmek"},
  {en: "Rhym", tr: "Uyak, kafiye"},
  {en: "ridicule", tr: "alay etmek"},
  {en: "Rink", tr: "Buz pisti"},
  {en: "Riot", tr: "İsyan"},
  {en: "Rip", tr: "Yırtmak"},
  {en: "Riptide", tr: "Dalga"},
  {en: "ritual", tr: "ayin"},
  {en: "Rivet", tr: "Perçin"},
  {en: "Roaches", tr: "Hamam böcekleri"},
  {en: "Rod", tr: "Çubuk"},
  {en: "Rook", tr: "Karga"},
  {en: "Rool", tr: "Yuvarlamak, yuvarlanmak"},
  {en: "Room", tr: "Oda, yer"},
  {en: "Rope", tr: "İp"},
  {en: "Rotten", tr: "Çürük"},
  {en: "Rough", tr: "Pürüzlü"},
  {en: "Rub", tr: "Fırça"},
  {en: "Rubber", tr: "Plastik"},
  {en: "Rubble", tr: "Moloz"},
  {en: "Rug", tr: "Kilim, halı"},
  {en: "Rugged", tr: "Engebeli"},
  {en: "rule out", tr: "göz ardı etmek"},
  {en: "Rumble", tr: "Uğultu"},
  {en: "Rumour", tr: "Rivayet"},
  {en: "Run", tr: "Pist"},
  {en: "Run for", tr: "Aday olmak"},
  {en: "run into", tr: "karşılaşmak"},
  {en: "Run low on", tr: "Birşeylerin azalması"},
  {en: "run out of", tr: "tüketmek"},
  {en: "Rundown", tr: "Yıkık, köhne"},
  {en: "Runner-up", tr: "İkinci"},
  {en: "Runny", tr: "Akan"},
  {en: "Runway", tr: "Uçak pisti"},
  {en: "Rural", tr: "Kırsal"},
  {en: "Rusty", tr: "Paslı"},
  {en: "ruthless", tr: "acımasız"},
  {en: "Sack (n)", tr: "Çuval bohça"},
  {en: "Sack (v) – argo", tr: "Kovmak"},
  {en: "sadistic", tr: "Sadist"},
  {en: "Sanction", tr: "Yaptırım"},
  {en: "Sanctuary", tr: "Mabet, sığınak"},
  {en: "Saturday", tr: "Cumartesi"},
  {en: "savor", tr: "Tadını çıkarmak"},
  {en: "Saw", tr: "Testere"},
  {en: "Saying", tr: "Deyim"},
  {en: "Scale", tr: "Baskül"},
  {en: "Scale back", tr: "Azaltmak"},
  {en: "scapegoat", tr: "günah keçisi"},
  {en: "Scarce", tr: "Az, kıt"},
  {en: "Scene", tr: "Olay yeri ,suç mahali"},
  {en: "Scenery", tr: "Manzara"},
  {en: "Scent", tr: "Koku"},
  {en: "Scoop", tr: "Kepçe"},
  {en: "Scrambled egg", tr: "Yağda pişmiş yumurta"},
  {en: "Scrape", tr: "Tırmalamak"},
  {en: "Scratch (n)", tr: "Çizik"},
  {en: "Scratch (v)", tr: "Tırmalamak"},
  {en: "Scrub", tr: "Kese, (fiil) ovmak"},
  {en: "Scrutinize (v)", tr: "İnce eleyip sık dokumak, didik didik araştırma"},
  {en: "Scrutiny", tr: "İnce eleyip sık dokumak, didik didik araştırma"},
  {en: "search for", tr: "aramak"},
  {en: "Seclusıon", tr: "Ayrı bölgelere koymak, tecrit"},
  {en: "seclusion", tr: "Inziva"},
  {en: "Secular", tr: "Laik"},
  {en: "sedate", tr: "Sakinleştirici"},
  {en: "Seek", tr: "Aramak"},
  {en: "Seek to V1 = try to V1", tr: "Çabalamak, çalışmak"},
  {en: "Seize", tr: "Yakalama"},
  {en: "Seize the day", tr: "Anı yakalama"},
  {en: "Self-esteem", tr: "Kendine sayfı"},
  {en: "send out", tr: "göndermek"},
  {en: "Senior class", tr: "Son sınıf"},
  {en: "Senseless", tr: "Manasız, saçma"},
  {en: "Sensible", tr: "Mantıklı"},
  {en: "Sentimental", tr: "Duygusal"},
  {en: "sequence", tr: "sıra"},
  {en: "set up", tr: "kurmak"},
  {en: "Settle", tr: "Fiyatta anlaşmak"},
  {en: "severity", tr: "şiddet"},
  {en: "Sew", tr: "Dikmek"},
  {en: "Sewage", tr: "Kanalizasyon, lağım"},
  {en: "Sewing", tr: "Dikiş"},
  {en: "Share", tr: "Hisse"},
  {en: "Shatter", tr: "Parçalamak, paramparça etmek"},
  {en: "Shed", tr: "Atmak (vücuttan)"},
  {en: "Shed tear", tr: "Gözyaşı dökmek"},
  {en: "Sheer", tr: "Tam, katıksız"},
  {en: "Sheet", tr: "Çarşaf"},
  {en: "Shelter", tr: "Sığınak"},
  {en: "Shepherd", tr: "Çoban"},
  {en: "Shiver", tr: "Titremek"},
  {en: "Shoot out", tr: "Fırlamak"},
  {en: "Shoot sb a dirty look (idiom)", tr: "Pis bakış atmak"},
  {en: "Shoplifter", tr: "Dükkandan mal çalan"},
  {en: "Shore", tr: "Göl kenarı"},
  {en: "Shovel", tr: "Küremek"},
  {en: "Show concern for", tr: "İlgi göstermek"},
  {en: "show off", tr: "hava atmak"},
  {en: "shrewd", tr: "kurnaz"},
  {en: "Shriek", tr: "Çığlık"},
  {en: "Shrimp", tr: "Karides"},
  {en: "Shrink", tr: "Daraltmak"},
  {en: "Shrub", tr: "Çalı"},
  {en: "Shut-in", tr: "Evden çıkamayan"},
  {en: "Shutter", tr: "Panjur"},
  {en: "Shuttle", tr: "Uzay mekiği"},
  {en: "Sideway", tr: "Kenar"},
  {en: "Siege", tr: "Kuşatma"},
  {en: "Sightseeing", tr: "Gezi"},
  {en: "Simply", tr: "Öylesine"},
  {en: "simultaneous", tr: "Eşzamanlı"},
  {en: "Sincere", tr: "Samimi"},
  {en: "Single-file", tr: "Tek sıra"},
  {en: "Sinister", tr: "Uğursuz"},
  {en: "site", tr: "site"},
  {en: "Sizeable", tr: "Büyük"},
  {en: "Sizzling", tr: "Yakıcı"},
  {en: "skeptical", tr: "Şüphe -ci"},
  {en: "Ski lift", tr: "Teksiyej"},
  {en: "Skydiving", tr: "Paraşütle atlamak"},
  {en: "Skyscraper", tr: "Gökdelen"},
  {en: "Slap", tr: "Tokat atmak"},
  {en: "Slaughtered", tr: "Katledilmiş"},
  {en: "Sleeve", tr: "Kol"},
  {en: "Slightest", tr: "En ufak"},
  {en: "Slim", tr: "Zayıf"},
  {en: "Sloppy", tr: "Derme çatma"},
  {en: "slow down", tr: "yavaşlamak"},
  {en: "Smash", tr: "Çarpmak"},
  {en: "Smuggle", tr: "Yurtdışına kaçırmak"},
  {en: "Snatch", tr: "Kapkaç"},
  {en: "Snatcher", tr: "Kapkaççı"},
  {en: "Sneakers", tr: "Spor ayakkabı"},
  {en: "Sniff", tr: "Koklamak"},
  {en: "Snobbish", tr: "Züppe"},
  {en: "Snore", tr: "Horlama"},
  {en: "Soak", tr: "Islatmak, ıslanmak (sırılsıklam)"},
  {en: "Sober", tr: "Ayık"},
  {en: "Soft tissue", tr: "Kağıt havlu"},
  {en: "Soil", tr: "Toprak"},
  {en: "Some time", tr: "Bir süre"},
  {en: "Soothing", tr: "Yatıştırıcı"},
  {en: "sophisticated", tr: "Sofistike"},
  {en: "Sore (exmp: throat)", tr: "Ağrılı, acılı"},
  {en: "Sound horn", tr: "Kornaya basmak"},
  {en: "Sour", tr: "Ekşi"},
  {en: "Span", tr: "Uzanmak"},
  {en: "Spark", tr: "Kıvılcım, kıvılcımı olmak, tetiklemek"},
  {en: "Sparrow", tr: "Serçe"},
  {en: "Sparse", tr: "Seyrek, az"},
  {en: "Spear", tr: "Ok"},
  {en: "Special event", tr: "Özel etkinlik"},
  {en: "Species (hem tekil hem çoğul)", tr: "Türler"},
  {en: "Spectacular", tr: "Görülmeye değer"},
  {en: "speed up", tr: "hızlandırmak"},
  {en: "Spill", tr: "Dökmek"},
  {en: "Spinach", tr: "Ispanak"},
  {en: "Spite", tr: "Nefret, kin"},
  {en: "Spiteful", tr: "Kinci"},
  {en: "Splash", tr: "Sıçratmak"},
  {en: "Spoil", tr: "Şımartmak, bozulmak (gıda)"},
  {en: "Spoilt", tr: "Şımarmak, bozulmak"},
  {en: "Spoonful", tr: "Kaşık dolusu"},
  {en: "Sprain", tr: "Burkulma"},
  {en: "Sprinkle", tr: "Çise"},
  {en: "Spurious", tr: "Sahte, çakma"},
  {en: "Squirrel", tr: "Sincap"},
  {en: "Stab", tr: "Saplamak"},
  {en: "Stable", tr: "Ahır"},
  {en: "Stack", tr: "Yığın (düzenli)"},
  {en: "Stagehand", tr: "Sahne görevlisi"},
  {en: "Stale", tr: "Bayat"},
  {en: "Stall", tr: "Tezgah"},
  {en: "Stand by", tr: "Görev"},
  {en: "stand for", tr: "simgelemek"},
  {en: "stand out", tr: "göze çarpmak"},
  {en: "Stand up", tr: "Direnmek"},
  {en: "stand up for", tr: "desteklemek"},
  {en: "Starring role", tr: "Başrol"},
  {en: "Stately", tr: "Görkemli"},
  {en: "Stationary", tr: "Kırtasiye"},
  {en: "stave off", tr: "bertaraf etmek"},
  {en: "Steady", tr: "Kalıcı"},
  {en: "Steamy", tr: "Buharlı"},
  {en: "Steep", tr: "Sarp, dik"},
  {en: "Steer", tr: "Yönlendirmek"},
  {en: "Steering wheel", tr: "Direksiyon"},
  {en: "Stem", tr: "Gövde"},
  {en: "stereotype", tr: "stereotip"},
  {en: "Stew", tr: "Yahni"},
  {en: "Stich", tr: "Dikiş"},
  {en: "stimulate", tr: "teşvik etmek"},
  {en: "Stinky", tr: "Leş gibi kokan"},
  {en: "Stir", tr: "Karıştırmak"},
  {en: "Stockbroker", tr: "Borsa simsarı"},
  {en: "Stoical (Marcus Aurelius)", tr: "Stoik, metanetli"},
  {en: "Stork", tr: "Leylek"},
  {en: "Stout", tr: "Tıknaz"},
  {en: "Strait", tr: "Boğaz"},
  {en: "Strap", tr: "Kayış"},
  {en: "strategy", tr: "strateji"},
  {en: "Straw", tr: "Pipet, saman"},
  {en: "Stray dog", tr: "Sokak köpeği"},
  {en: "Stream", tr: "Dere"},
  {en: "Stretch", tr: "Uzantı"},
  {en: "Stretch out", tr: "Uzanmak"},
  {en: "Stretcher", tr: "Sedye"},
  {en: "Strict", tr: "Katı"},
  {en: "Stuck", tr: "Sıkışmış"},
  {en: "Stud", tr: "Hızma"},
  {en: "Stuffing", tr: "İçi doldurulmuş"},
  {en: "Stutter", tr: "Kekeleme"},
  {en: "submit", tr: "Gönder"},
  {en: "Subsequent", tr: "Ardışık, sonraki"},
  {en: "subside", tr: "Azal"},
  {en: "Subsidies", tr: "Sübvansiyon, parasal destek"},
  {en: "Substitute", tr: "Yerine koymak"},
  {en: "subtle", tr: "mâhirâne"},
  {en: "Subversive", tr: "Yıkıcı"},
  {en: "Succinct", tr: "Kısa ve öz"},
  {en: "Such as", tr: "Örneğin"},
  {en: "Suede", tr: "Süet"},
  {en: "Suffering", tr: "Istırap"},
  {en: "Suffice", tr: "Yeterli olmak, yeterli gelmek"},
  {en: "Suffrage", tr: "Oy kullanma"},
  {en: "Suit + kıyafet", tr: "Yakışmak"},
  {en: "Sulk", tr: "Somurtmak"},
  {en: "summon", tr: "çağırmak"},
  {en: "superficial", tr: "yüzeysel"},
  {en: "supplement", tr: "ek"},
  {en: "Supply", tr: "Malzeme, erzak"},
  {en: "Support", tr: "Desteklemek"},
  {en: "Suppose", tr: "Diyelimki"},
  {en: "Sure-fire", tr: "Garanti, kesin"},
  {en: "Surface", tr: "Yüzey"},
  {en: "surpass", tr: "geçmek"},
  {en: "susceptible", tr: "duyarlı"},
  {en: "Suspend", tr: "Uzaklaştırma"},
  {en: "Suspense movie", tr: "Gerilim filmi"},
  {en: "sustain", tr: "sürdürmek"},
  {en: "Sustainable", tr: "Sürdürülebilir"},
  {en: "Swallow", tr: "Kırlangıç"},
  {en: "Sweat", tr: "Ter"},
  {en: "Sweep", tr: "Süpürmek"},
  {en: "Swiftly", tr: "Hızlıca"},
  {en: "Switcboard", tr: "Santral"},
  {en: "Syrup", tr: "Şurup"},
  {en: "tactic", tr: "Taktik"},
  {en: "Take … for granted", tr: "Sıradanlaştırmak"},
  {en: "Take a tool on", tr: "Bedel ödetmek"},
  {en: "Take a vicarious pleasure in", tr: "Başkasının adına mutlu olmak"},
  {en: "take after", tr: "benzemek"},
  {en: "take off", tr: "çıkarmak"},
  {en: "take on", tr: "üstlenmek"},
  {en: "take over", tr: "devralmak"},
  {en: "take part in", tr: "katılmak"},
  {en: "Take so long", tr: "Oyalanmak"},
  {en: "Take turn", tr: "Sırayla yapma"},
  {en: "take up", tr: "başlamak (hobi)"},
  {en: "Take up = start", tr: "Alım = başlat"},
  {en: "Tap", tr: "Musluk"},
  {en: "Tar", tr: "Tar"},
  {en: "Tariff", tr: "Gümrük vergisi"},
  {en: "Task", tr: "Görev"},
  {en: "Teas", tr: "Takılmak, dalga geçmek"},
  {en: "Tease", tr: "Takılmak (şaka olarak)"},
  {en: "Technically", tr: "Aslında"},
  {en: "tedious", tr: "sıkıcı"},
  {en: "Temper", tr: "Sinir, sinirli, kızgın"},
  {en: "Temptation", tr: "Baştan çıkarma, ayartma"},
  {en: "tentative", tr: "tecrübe"},
  {en: "Tenure", tr: "Görev süresi"},
  {en: "Terrain", tr: "Arazi"},
  {en: "Terrestrial", tr: "Yeryüzüyle ilgili"},
  {en: "Testify", tr: "Tanıklık etmek"},
  {en: "That is", tr: "Yani"},
  {en: "That is all the more reason to V1", tr: "Daha da büyük bir sebep"},
  {en: "The only", tr: "Tek"},
  {en: "The other day", tr: "Geçen gün"},
  {en: "The way", tr: "Tarz, şekil"},
  {en: "theoretical", tr: "teorik"},
  {en: "Thorn", tr: "Diken"},
  {en: "Thoroughly", tr: "Tamamen"},
  {en: "Those + prep Örn: those in need", tr: "Ler, lar, muhtaçlar"},
  {en: "Thread", tr: "İplik"},
  {en: "Through", tr: "İçinden"},
  {en: "Ticket", tr: "Trafik cezası"},
  {en: "Timber", tr: "Kereste"},
  {en: "Time being", tr: "Bir süreliğine, şimdilik"},
  {en: "Timid", tr: "Utangaç, ürkek"},
  {en: "Tiny", tr: "Minik"},
  {en: "Tipsy", tr: "Çakırkeyif"},
  {en: "Tirelessly", tr: "Yorulmadan"},
  {en: "Tissue", tr: "1. Doku 2. Kağıt mendil"},
  {en: "To make a long stroy short", tr: "Uzun lafın kısası"},
  {en: "To make ends meet", tr: "Ayın sonunu getirmek"},
  {en: "To my surprise", tr: "Bir de ne göreyim"},
  {en: "To some degree", tr: "Bir dereceye kadar"},
  {en: "To the point", tr: "Tam üstüne basar, alakalı"},
  {en: "To what extent?", tr: "Ne dereceye kadar"},
  {en: "Toil up", tr: "Öfleye pöfleye çıkmak"},
  {en: "Tomb", tr: "Anıt mezar"},
  {en: "Too … to V1", tr: "Yapamayacak kadar"},
  {en: "Torrential", tr: "Sağanak"},
  {en: "Torture", tr: "İşgence etmek"},
  {en: "Toss", tr: "Atmak (top vb)"},
  {en: "Tough", tr: "Sert"},
  {en: "Trace", tr: "İzini sürmek"},
  {en: "Track", tr: "Bulaştırmak"},
  {en: "Track sb down", tr: "Takip edip bulmak"},
  {en: "Trade for", tr: "Takas etmek"},
  {en: "Traffic jam", tr: "Trafik sıkışıklığı"},
  {en: "Trail", tr: "Deneme, duruşma"},
  {en: "Trait", tr: "Karakter"},
  {en: "transaction", tr: "işlem"},
  {en: "transition", tr: "geçiş"},
  {en: "transmit", tr: "iletmek"},
  {en: "Tray", tr: "Tepsi"},
  {en: "treacherous", tr: "hain"},
  {en: "Tread - trod (V2)", tr: "Üzerine basmak"},
  {en: "Treat", tr: "Davranmak, tedavi etmek, ısmarlamak"},
  {en: "Treaty", tr: "Anlaşma"},
  {en: "Tribe", tr: "Kabile"},
  {en: "Trip over", tr: "Ayağı takılıp düşmek"},
  {en: "Triumph", tr: "Zafer"},
  {en: "trivial", tr: "Önem -siz"},
  {en: "Trophy", tr: "Tac"},
  {en: "Troublemaker", tr: "Başbelası"},
  {en: "Try hard", tr: "Çok çabalamak"},
  {en: "Tub", tr: "Küvet"},
  {en: "Tune", tr: "Melodi"},
  {en: "Turmoil", tr: "Hengame, karışıklık"},
  {en: "turn down", tr: "reddetmek"},
  {en: "turn into", tr: "…e dönüştürmek"},
  {en: "Turn out", tr: "Olduğu ortaya çıkmak"},
  {en: "Tutor", tr: "Öğretmen (özel ders)"},
  {en: "Typeset", tr: "Dizgi"},
  {en: "Unclaimed", tr: "Sahipsiz"},
  {en: "Under the circumstances", tr: "Bu koşullar altında"},
  {en: "undermine", tr: "Zayıflatmak"},
  {en: "Underpass", tr: "Alt geçit"},
  {en: "Unequaled", tr: "Eşsiz"},
  {en: "Uneven", tr: "Engebeli"},
  {en: "Unfair", tr: "Adaletsiz, haksız"},
  {en: "Ungracefully", tr: "Kabaca"},
  {en: "Unified", tr: "Birlik"},
  {en: "unique", tr: "eşsiz"},
  {en: "universal", tr: "evrensel"},
  {en: "Unleash", tr: "Salmak, serbest brakmak"},
  {en: "Unprecedented", tr: "Benzersiz"},
  {en: "Unrest", tr: "Huzursuzluk"},
  {en: "Unspoilt", tr: "Bozulmamış, el değmemiş"},
  {en: "Up to no good", tr: "Haylazlık peşinde"},
  {en: "Upbringing", tr: "Büyüme, yetişme dönemi"},
  {en: "Uproar", tr: "Hengame, karışıklık"},
  {en: "Upside", tr: "Pozitif taraf"},
  {en: "urban", tr: "kentsel"},
  {en: "Urge", tr: "Israrla istemek"},
  {en: "use up", tr: "tüketmek"},
  {en: "Utensil", tr: "Alet edevat, mutfak araçları"},
  {en: "Vacation", tr: "Tatil"},
  {en: "Vacuuming", tr: "Süpürme"},
  {en: "Vain", tr: "Kibir"},
  {en: "valid", tr: "geçerli"},
  {en: "Vaugely", tr: "Belli belirsiz"},
  {en: "Veal", tr: "Sığır eti"},
  {en: "Vend", tr: "Sokak satıcısı"},
  {en: "Vent", tr: "Havalandırmak"},
  {en: "Venue", tr: "Olay yeri"},
  {en: "Verdict", tr: "Son karar"},
  {en: "verify", tr: "doğrulamak"},
  {en: "versatile", tr: "Çok yönlü"},
  {en: "Verse", tr: "Dize"},
  {en: "Vest", tr: "Yelek"},
  {en: "Vestige", tr: "İz"},
  {en: "Vibrant", tr: "Canlı"},
  {en: "Vicarious", tr: "Adına"},
  {en: "Vicinity", tr: "Etraf, civar, çevre"},
  {en: "Vicious", tr: "Şirret, ahlaksız"},
  {en: "vigorous", tr: "Güçlü"},
  {en: "Vigorous", tr: "Enerjik"},
  {en: "Vigorously", tr: "Canla başla, gayretle"},
  {en: "Vile", tr: "Pis, adi, aşağılık"},
  {en: "Vile slander", tr: "Pis iftira"},
  {en: "Vim", tr: "Coşku"},
  {en: "Vine", tr: "Asma, üzüm bağı"},
  {en: "Violet", tr: "Menekşe"},
  {en: "Viper", tr: "Sinsi, yılan"},
  {en: "Virtue", tr: "Erdem, fazilet"},
  {en: "vital", tr: "yaşamsal"},
  {en: "vivid", tr: "Canlı"},
  {en: "vocation", tr: "meslek"},
  {en: "Voluminous", tr: "Hacimli"},
  {en: "Wages", tr: "Ücretler"},
  {en: "Wagging tail", tr: "Kuyruk sallamak"},
  {en: "Waist", tr: "Bel"},
  {en: "Waistcoat", tr: "Palto"},
  {en: "Walking down the aisle", tr: "Evlenmek"},
  {en: "Wander", tr: "Gezinme"},
  {en: "Wane", tr: "Azalmak"},
  {en: "ward off", tr: "defetmek"},
  {en: "Warm up", tr: "Isınmak"},
  {en: "Wary", tr: "Dikkatli, ihtiyatlı"},
  {en: "Wasp", tr: "Eşek arısı"},
  {en: "Wast", tr: "Ziyan etmek"},
  {en: "Waste bin", tr: "Çöp kutusu"},
  {en: "Watch scheme", tr: "Nöbet çizelgesi"},
  {en: "Wave", tr: "El sallamak"},
  {en: "Way to go", tr: "Yürü be"},
  {en: "Wealth", tr: "Zenginlik"},
  {en: "Wear away", tr: "Aşındırmak"},
  {en: "wear out", tr: "yıpranmak"},
  {en: "Weave", tr: "Dokumak"},
  {en: "Wedding gown", tr: "Gelinlik"},
  {en: "Weed", tr: "Yabani ot"},
  {en: "Welfare", tr: "Refah"},
  {en: "Well-off", tr: "Hali vakti yerinde"},
  {en: "Wend", tr: "Ağır ve yavaş adımla gitmek"},
  {en: "What it takes", tr: "Ne gerekiyorsa"},
  {en: "Wheat", tr: "Buğday"},
  {en: "Whim", tr: "Kapris, kaprisli istek"},
  {en: "Whipp", tr: "Çırpmak"},
  {en: "Whisker", tr: "Bıyık"},
  {en: "Whole grains", tr: "Tam tahıllar"},
  {en: "Wide awake", tr: "Tamamen ayık"},
  {en: "Widow", tr: "Dul"},
  {en: "Wild fires", tr: "Orman yangını"},
  {en: "Wilderness", tr: "El değmemişlik"},
  {en: "Will", tr: "Vasiyet"},
  {en: "Wilt", tr: "solmak"},
  {en: "Windowsill", tr: "Pencere eşiği"},
  {en: "Windshield", tr: "Arabanın ön camı"},
  {en: "Wink", tr: "Göz kırpmak"},
  {en: "wipe out", tr: "kökünü kazımak"},
  {en: "Wired for", tr: "Adapte olmuş"},
  {en: "Wisdom", tr: "Bilgelik"},
  {en: "Wisdom teeth", tr: "20 yaş dişi"},
  {en: "With KONU in mind", tr: "Konu hesaba katılarak, dikkate alınarak"},
  {en: "With the advent", tr: "Ortaya çıkmasıyla"},
  {en: "Withstand", tr: "Dayanma, direnme"},
  {en: "Witness", tr: "Tanık olmak, tanık"},
  {en: "Wolf", tr: "Kurt"},
  {en: "Wondrous", tr: "Mükemmel"},
  {en: "Wool", tr: "Yün"},
  {en: "Word", tr: "Turkish Meaning"},
  {en: "Wordy", tr: "Geveze"},
  {en: "Worn out", tr: "Bitkin"},
  {en: "Worship", tr: "Tapmak"},
  {en: "Would rather", tr: "Tercih etmek"},
  {en: "Would you mind", tr: "Sakıncası var mı"},
  {en: "Wrap", tr: "Sarmak, dolamak"},
  {en: "Wrath", tr: "Gazap"},
  {en: "Wrekage", tr: "Enkaz"},
  {en: "Wrinkle", tr: "Kırışıklık"},
  {en: "Yank", tr: "Sertçe çekmek"},
  {en: "Yarn", tr: "İplik"},
  {en: "Yawn", tr: "Esnemek"},
  {en: "Yearn for", tr: "Aşermek"},
  {en: "Zeal", tr: "Şevk, heyecanlı istek, tutku"},
  {en: "Zealous", tr: "İstekli"},
];
